var annotated_dup =
[
    [ "Float16Utils", "namespaceFloat16Utils.html", [
      [ "Float16ConversionStats", "structFloat16Utils_1_1Float16ConversionStats.html", "structFloat16Utils_1_1Float16ConversionStats" ],
      [ "QuantizationChunk", "structFloat16Utils_1_1QuantizationChunk.html", "structFloat16Utils_1_1QuantizationChunk" ]
    ] ],
    [ "GaussianRenderConfig", "namespaceGaussianRenderConfig.html", [
      [ "CullingConfig", "structGaussianRenderConfig_1_1CullingConfig.html", "structGaussianRenderConfig_1_1CullingConfig" ],
      [ "InteractiveStateConfig", "structGaussianRenderConfig_1_1InteractiveStateConfig.html", "structGaussianRenderConfig_1_1InteractiveStateConfig" ],
      [ "PainterlyConfig", "structGaussianRenderConfig_1_1PainterlyConfig.html", "structGaussianRenderConfig_1_1PainterlyConfig" ],
      [ "RenderConfig", "structGaussianRenderConfig_1_1RenderConfig.html", "structGaussianRenderConfig_1_1RenderConfig" ],
      [ "StateUniformData", "structGaussianRenderConfig_1_1StateUniformData.html", "structGaussianRenderConfig_1_1StateUniformData" ]
    ] ],
    [ "GaussianRenderDebug", "namespaceGaussianRenderDebug.html", [
      [ "DebugConfig", "structGaussianRenderDebug_1_1DebugConfig.html", "structGaussianRenderDebug_1_1DebugConfig" ],
      [ "DebugConfigBase", "structGaussianRenderDebug_1_1DebugConfigBase.html", "structGaussianRenderDebug_1_1DebugConfigBase" ],
      [ "DebugState", "structGaussianRenderDebug_1_1DebugState.html", "structGaussianRenderDebug_1_1DebugState" ],
      [ "JacobianDebugConfig", "structGaussianRenderDebug_1_1JacobianDebugConfig.html", "structGaussianRenderDebug_1_1JacobianDebugConfig" ],
      [ "SplatAuditSummary", "structGaussianRenderDebug_1_1SplatAuditSummary.html", "structGaussianRenderDebug_1_1SplatAuditSummary" ]
    ] ],
    [ "GaussianRenderFacadeState", "namespaceGaussianRenderFacadeState.html", [
      [ "DeviceState", "structGaussianRenderFacadeState_1_1DeviceState.html", "structGaussianRenderFacadeState_1_1DeviceState" ],
      [ "ResourceState", "structGaussianRenderFacadeState_1_1ResourceState.html", "structGaussianRenderFacadeState_1_1ResourceState" ],
      [ "ShadowBlitState", "structGaussianRenderFacadeState_1_1ShadowBlitState.html", "structGaussianRenderFacadeState_1_1ShadowBlitState" ],
      [ "SubsystemState", "structGaussianRenderFacadeState_1_1SubsystemState.html", "structGaussianRenderFacadeState_1_1SubsystemState" ],
      [ "TestDataState", "structGaussianRenderFacadeState_1_1TestDataState.html", "structGaussianRenderFacadeState_1_1TestDataState" ],
      [ "TileRendererState", "structGaussianRenderFacadeState_1_1TileRendererState.html", "structGaussianRenderFacadeState_1_1TileRendererState" ]
    ] ],
    [ "GaussianRenderFrame", "namespaceGaussianRenderFrame.html", [
      [ "CrossDeviceOperation", "structGaussianRenderFrame_1_1CrossDeviceOperation.html", "structGaussianRenderFrame_1_1CrossDeviceOperation" ],
      [ "DiagnosticsState", "structGaussianRenderFrame_1_1DiagnosticsState.html", "structGaussianRenderFrame_1_1DiagnosticsState" ],
      [ "ErrorRecoveryStateMachine", "structGaussianRenderFrame_1_1ErrorRecoveryStateMachine.html", "structGaussianRenderFrame_1_1ErrorRecoveryStateMachine" ],
      [ "FrameTimingSample", "structGaussianRenderFrame_1_1FrameTimingSample.html", "structGaussianRenderFrame_1_1FrameTimingSample" ],
      [ "RuntimeErrorStatistics", "structGaussianRenderFrame_1_1RuntimeErrorStatistics.html", "structGaussianRenderFrame_1_1RuntimeErrorStatistics" ],
      [ "TextureTraceEntry", "structGaussianRenderFrame_1_1TextureTraceEntry.html", "structGaussianRenderFrame_1_1TextureTraceEntry" ]
    ] ],
    [ "GaussianRenderPerformance", "namespaceGaussianRenderPerformance.html", [
      [ "PerformanceMetrics", "structGaussianRenderPerformance_1_1PerformanceMetrics.html", "structGaussianRenderPerformance_1_1PerformanceMetrics" ],
      [ "PerformanceSettings", "structGaussianRenderPerformance_1_1PerformanceSettings.html", "structGaussianRenderPerformance_1_1PerformanceSettings" ],
      [ "PerformanceState", "structGaussianRenderPerformance_1_1PerformanceState.html", "structGaussianRenderPerformance_1_1PerformanceState" ],
      [ "SortFrameMetrics", "structGaussianRenderPerformance_1_1SortFrameMetrics.html", "structGaussianRenderPerformance_1_1SortFrameMetrics" ]
    ] ],
    [ "GaussianRenderPipeline", "namespaceGaussianRenderPipeline.html", [
      [ "DataSourcePlan", "structGaussianRenderPipeline_1_1DataSourcePlan.html", "structGaussianRenderPipeline_1_1DataSourcePlan" ],
      [ "InstancePipelineBuffers", "structGaussianRenderPipeline_1_1InstancePipelineBuffers.html", "structGaussianRenderPipeline_1_1InstancePipelineBuffers" ],
      [ "PainterlyCompositePushConstant", "structGaussianRenderPipeline_1_1PainterlyCompositePushConstant.html", "structGaussianRenderPipeline_1_1PainterlyCompositePushConstant" ],
      [ "PipelineEvent", "structGaussianRenderPipeline_1_1PipelineEvent.html", "structGaussianRenderPipeline_1_1PipelineEvent" ],
      [ "PublishedInstanceAssetRemap", "structGaussianRenderPipeline_1_1PublishedInstanceAssetRemap.html", "structGaussianRenderPipeline_1_1PublishedInstanceAssetRemap" ],
      [ "RasterStageOutput", "structGaussianRenderPipeline_1_1RasterStageOutput.html", "structGaussianRenderPipeline_1_1RasterStageOutput" ],
      [ "RenderFramePlan", "structGaussianRenderPipeline_1_1RenderFramePlan.html", "structGaussianRenderPipeline_1_1RenderFramePlan" ],
      [ "RenderFrameSnapshot", "structGaussianRenderPipeline_1_1RenderFrameSnapshot.html", "structGaussianRenderPipeline_1_1RenderFrameSnapshot" ],
      [ "RenderRouteDecision", "structGaussianRenderPipeline_1_1RenderRouteDecision.html", "structGaussianRenderPipeline_1_1RenderRouteDecision" ],
      [ "SortStageOutput", "structGaussianRenderPipeline_1_1SortStageOutput.html", "structGaussianRenderPipeline_1_1SortStageOutput" ],
      [ "SplatDataSource", "structGaussianRenderPipeline_1_1SplatDataSource.html", "structGaussianRenderPipeline_1_1SplatDataSource" ],
      [ "StageIO", "structGaussianRenderPipeline_1_1StageIO.html", "structGaussianRenderPipeline_1_1StageIO" ],
      [ "StageMetrics", "structGaussianRenderPipeline_1_1StageMetrics.html", "structGaussianRenderPipeline_1_1StageMetrics" ],
      [ "StageResult", "structGaussianRenderPipeline_1_1StageResult.html", "structGaussianRenderPipeline_1_1StageResult" ]
    ] ],
    [ "GaussianRenderState", "namespaceGaussianRenderState.html", [
      [ "CullStageOutput", "structGaussianRenderState_1_1CullStageOutput.html", "structGaussianRenderState_1_1CullStageOutput" ],
      [ "SceneState", "structGaussianRenderState_1_1SceneState.html", "structGaussianRenderState_1_1SceneState" ],
      [ "SortingState", "structGaussianRenderState_1_1SortingState.html", "structGaussianRenderState_1_1SortingState" ],
      [ "SortStageSummary", "structGaussianRenderState_1_1SortStageSummary.html", "structGaussianRenderState_1_1SortStageSummary" ],
      [ "StreamingState", "structGaussianRenderState_1_1StreamingState.html", "structGaussianRenderState_1_1StreamingState" ]
    ] ],
    [ "GaussianSplatting", "namespaceGaussianSplatting.html", [
      [ "ComputeInfrastructure", "namespaceGaussianSplatting_1_1ComputeInfrastructure.html", [
        [ "CapabilityGatePolicy", "structGaussianSplatting_1_1ComputeInfrastructure_1_1CapabilityGatePolicy.html", "structGaussianSplatting_1_1ComputeInfrastructure_1_1CapabilityGatePolicy" ],
        [ "FallbackDecision", "structGaussianSplatting_1_1ComputeInfrastructure_1_1FallbackDecision.html", "structGaussianSplatting_1_1ComputeInfrastructure_1_1FallbackDecision" ],
        [ "StageResult", "structGaussianSplatting_1_1ComputeInfrastructure_1_1StageResult.html", "structGaussianSplatting_1_1ComputeInfrastructure_1_1StageResult" ],
        [ "StageValidationHarness", "classGaussianSplatting_1_1ComputeInfrastructure_1_1StageValidationHarness.html", "classGaussianSplatting_1_1ComputeInfrastructure_1_1StageValidationHarness" ],
        [ "StageValidationInput", "structGaussianSplatting_1_1ComputeInfrastructure_1_1StageValidationInput.html", "structGaussianSplatting_1_1ComputeInfrastructure_1_1StageValidationInput" ],
        [ "StageValidationRecord", "structGaussianSplatting_1_1ComputeInfrastructure_1_1StageValidationRecord.html", "structGaussianSplatting_1_1ComputeInfrastructure_1_1StageValidationRecord" ],
        [ "UniformBindingContract", "structGaussianSplatting_1_1ComputeInfrastructure_1_1UniformBindingContract.html", "structGaussianSplatting_1_1ComputeInfrastructure_1_1UniformBindingContract" ]
      ] ],
      [ "InstancePipelineContract", "namespaceGaussianSplatting_1_1InstancePipelineContract.html", [
        [ "InvariantViolation", "structGaussianSplatting_1_1InstancePipelineContract_1_1InvariantViolation.html", "structGaussianSplatting_1_1InstancePipelineContract_1_1InvariantViolation" ]
      ] ],
      [ "AnimationChange", "structGaussianSplatting_1_1AnimationChange.html", "structGaussianSplatting_1_1AnimationChange" ],
      [ "AnimationClip", "structGaussianSplatting_1_1AnimationClip.html", "structGaussianSplatting_1_1AnimationClip" ],
      [ "AnimationTrack", "structGaussianSplatting_1_1AnimationTrack.html", "structGaussianSplatting_1_1AnimationTrack" ],
      [ "AssetReference", "structGaussianSplatting_1_1AssetReference.html", "structGaussianSplatting_1_1AssetReference" ],
      [ "BufferOwnership", "structGaussianSplatting_1_1BufferOwnership.html", "structGaussianSplatting_1_1BufferOwnership" ],
      [ "ChangeEntry", "structGaussianSplatting_1_1ChangeEntry.html", "structGaussianSplatting_1_1ChangeEntry" ],
      [ "ChunkHeader", "structGaussianSplatting_1_1ChunkHeader.html", "structGaussianSplatting_1_1ChunkHeader" ],
      [ "GaussianAnimationStateMachine", "classGaussianSplatting_1_1GaussianAnimationStateMachine.html", "classGaussianSplatting_1_1GaussianAnimationStateMachine" ],
      [ "GaussianData", "structGaussianSplatting_1_1GaussianData.html", "structGaussianSplatting_1_1GaussianData" ],
      [ "GaussianIncrementalSaver", "classGaussianSplatting_1_1GaussianIncrementalSaver.html", "classGaussianSplatting_1_1GaussianIncrementalSaver" ],
      [ "GaussianSceneSerializer", "classGaussianSplatting_1_1GaussianSceneSerializer.html", "classGaussianSplatting_1_1GaussianSceneSerializer" ],
      [ "GaussianSplatLODConfig", "structGaussianSplatting_1_1GaussianSplatLODConfig.html", "structGaussianSplatting_1_1GaussianSplatLODConfig" ],
      [ "GaussianSplatStreamingConfig", "structGaussianSplatting_1_1GaussianSplatStreamingConfig.html", "structGaussianSplatting_1_1GaussianSplatStreamingConfig" ],
      [ "HierarchicalSplatStructure", "classGaussianSplatting_1_1HierarchicalSplatStructure.html", "classGaussianSplatting_1_1HierarchicalSplatStructure" ],
      [ "IndirectDispatchLayout", "structGaussianSplatting_1_1IndirectDispatchLayout.html", "structGaussianSplatting_1_1IndirectDispatchLayout" ],
      [ "Keyframe", "structGaussianSplatting_1_1Keyframe.html", "structGaussianSplatting_1_1Keyframe" ],
      [ "KeyframeInterpolator", "classGaussianSplatting_1_1KeyframeInterpolator.html", "classGaussianSplatting_1_1KeyframeInterpolator" ],
      [ "PainterlyManager", "classGaussianSplatting_1_1PainterlyManager.html", "classGaussianSplatting_1_1PainterlyManager" ],
      [ "PainterlyMetadata", "structGaussianSplatting_1_1PainterlyMetadata.html", "structGaussianSplatting_1_1PainterlyMetadata" ],
      [ "PassColors", "structGaussianSplatting_1_1PassColors.html", null ],
      [ "SceneHeader", "structGaussianSplatting_1_1SceneHeader.html", "structGaussianSplatting_1_1SceneHeader" ],
      [ "ScopedGpuMarker", "classGaussianSplatting_1_1ScopedGpuMarker.html", "classGaussianSplatting_1_1ScopedGpuMarker" ],
      [ "ScopedGpuMarkerEx", "classGaussianSplatting_1_1ScopedGpuMarkerEx.html", "classGaussianSplatting_1_1ScopedGpuMarkerEx" ],
      [ "SortBenchmarkTimingMetrics", "structGaussianSplatting_1_1SortBenchmarkTimingMetrics.html", "structGaussianSplatting_1_1SortBenchmarkTimingMetrics" ],
      [ "SortFallbackPolicyDecision", "structGaussianSplatting_1_1SortFallbackPolicyDecision.html", "structGaussianSplatting_1_1SortFallbackPolicyDecision" ],
      [ "SortKey64", "structGaussianSplatting_1_1SortKey64.html", "structGaussianSplatting_1_1SortKey64" ],
      [ "SortPaddingInfo", "structGaussianSplatting_1_1SortPaddingInfo.html", "structGaussianSplatting_1_1SortPaddingInfo" ],
      [ "SphereEffectorRenderData", "structGaussianSplatting_1_1SphereEffectorRenderData.html", "structGaussianSplatting_1_1SphereEffectorRenderData" ],
      [ "SplatChange", "structGaussianSplatting_1_1SplatChange.html", "structGaussianSplatting_1_1SplatChange" ],
      [ "ThreadOwnedMutex", "classGaussianSplatting_1_1ThreadOwnedMutex.html", "classGaussianSplatting_1_1ThreadOwnedMutex" ],
      [ "ThreadOwnedMutexLock", "classGaussianSplatting_1_1ThreadOwnedMutexLock.html", "classGaussianSplatting_1_1ThreadOwnedMutexLock" ],
      [ "TileAdaptiveSettings", "structGaussianSplatting_1_1TileAdaptiveSettings.html", "structGaussianSplatting_1_1TileAdaptiveSettings" ],
      [ "TileBufferResizePlan", "structGaussianSplatting_1_1TileBufferResizePlan.html", "structGaussianSplatting_1_1TileBufferResizePlan" ],
      [ "TileBufferShrinkPolicy", "structGaussianSplatting_1_1TileBufferShrinkPolicy.html", "structGaussianSplatting_1_1TileBufferShrinkPolicy" ],
      [ "TileConfigState", "structGaussianSplatting_1_1TileConfigState.html", "structGaussianSplatting_1_1TileConfigState" ],
      [ "TileDebugCounterSnapshot", "structGaussianSplatting_1_1TileDebugCounterSnapshot.html", "structGaussianSplatting_1_1TileDebugCounterSnapshot" ],
      [ "TileDensityMetrics", "structGaussianSplatting_1_1TileDensityMetrics.html", "structGaussianSplatting_1_1TileDensityMetrics" ],
      [ "TileDeviceContext", "structGaussianSplatting_1_1TileDeviceContext.html", "structGaussianSplatting_1_1TileDeviceContext" ],
      [ "TileDiagnosticsState", "structGaussianSplatting_1_1TileDiagnosticsState.html", "structGaussianSplatting_1_1TileDiagnosticsState" ],
      [ "TileFrameState", "structGaussianSplatting_1_1TileFrameState.html", "structGaussianSplatting_1_1TileFrameState" ],
      [ "TileGlobalSortResources", "structGaussianSplatting_1_1TileGlobalSortResources.html", "structGaussianSplatting_1_1TileGlobalSortResources" ],
      [ "TileGridState", "structGaussianSplatting_1_1TileGridState.html", "structGaussianSplatting_1_1TileGridState" ],
      [ "TileLightingClusterABIConfig", "structGaussianSplatting_1_1TileLightingClusterABIConfig.html", "structGaussianSplatting_1_1TileLightingClusterABIConfig" ],
      [ "TileLightingSetABI", "structGaussianSplatting_1_1TileLightingSetABI.html", null ],
      [ "TileOverflowStatsSnapshot", "structGaussianSplatting_1_1TileOverflowStatsSnapshot.html", "structGaussianSplatting_1_1TileOverflowStatsSnapshot" ],
      [ "TilePerformanceMetrics", "structGaussianSplatting_1_1TilePerformanceMetrics.html", "structGaussianSplatting_1_1TilePerformanceMetrics" ],
      [ "TilePrefixCpuScanResult", "structGaussianSplatting_1_1TilePrefixCpuScanResult.html", "structGaussianSplatting_1_1TilePrefixCpuScanResult" ],
      [ "TilePrefixDispatchCounts", "structGaussianSplatting_1_1TilePrefixDispatchCounts.html", "structGaussianSplatting_1_1TilePrefixDispatchCounts" ],
      [ "TilePrefixParamsLayout", "structGaussianSplatting_1_1TilePrefixParamsLayout.html", "structGaussianSplatting_1_1TilePrefixParamsLayout" ],
      [ "TilePrefixPass2ControlLayout", "structGaussianSplatting_1_1TilePrefixPass2ControlLayout.html", "structGaussianSplatting_1_1TilePrefixPass2ControlLayout" ],
      [ "TileProjectionBuffers", "structGaussianSplatting_1_1TileProjectionBuffers.html", "structGaussianSplatting_1_1TileProjectionBuffers" ],
      [ "TileRenderParams", "structGaussianSplatting_1_1TileRenderParams.html", "structGaussianSplatting_1_1TileRenderParams" ],
      [ "TileRenderSettings", "structGaussianSplatting_1_1TileRenderSettings.html", "structGaussianSplatting_1_1TileRenderSettings" ],
      [ "TileRenderStats", "structGaussianSplatting_1_1TileRenderStats.html", "structGaussianSplatting_1_1TileRenderStats" ],
      [ "TileRenderTargets", "structGaussianSplatting_1_1TileRenderTargets.html", "structGaussianSplatting_1_1TileRenderTargets" ],
      [ "TileResourceController", "structGaussianSplatting_1_1TileResourceController.html", "structGaussianSplatting_1_1TileResourceController" ],
      [ "TileSceneLightingInputs", "structGaussianSplatting_1_1TileSceneLightingInputs.html", "structGaussianSplatting_1_1TileSceneLightingInputs" ],
      [ "TileShaderResources", "structGaussianSplatting_1_1TileShaderResources.html", "structGaussianSplatting_1_1TileShaderResources" ],
      [ "TileSHCacheBuffers", "structGaussianSplatting_1_1TileSHCacheBuffers.html", "structGaussianSplatting_1_1TileSHCacheBuffers" ],
      [ "TileSplatAuditSnapshot", "structGaussianSplatting_1_1TileSplatAuditSnapshot.html", "structGaussianSplatting_1_1TileSplatAuditSnapshot" ],
      [ "TileSubpixelHistoryBuffers", "structGaussianSplatting_1_1TileSubpixelHistoryBuffers.html", "structGaussianSplatting_1_1TileSubpixelHistoryBuffers" ],
      [ "TileSubpixelVisibilityBuffers", "structGaussianSplatting_1_1TileSubpixelVisibilityBuffers.html", "structGaussianSplatting_1_1TileSubpixelVisibilityBuffers" ],
      [ "TileTimestampRange", "structGaussianSplatting_1_1TileTimestampRange.html", "structGaussianSplatting_1_1TileTimestampRange" ],
      [ "TileTimingState", "structGaussianSplatting_1_1TileTimingState.html", "structGaussianSplatting_1_1TileTimingState" ],
      [ "TileUniformBuffers", "structGaussianSplatting_1_1TileUniformBuffers.html", "structGaussianSplatting_1_1TileUniformBuffers" ]
    ] ],
    [ "GaussianStreamingTypes", "namespaceGaussianStreamingTypes.html", [
      [ "AssetRegistryState", "structGaussianStreamingTypes_1_1AssetRegistryState.html", "structGaussianStreamingTypes_1_1AssetRegistryState" ],
      [ "AtlasAssetState", "structGaussianStreamingTypes_1_1AtlasAssetState.html", "structGaussianStreamingTypes_1_1AtlasAssetState" ],
      [ "BudgetState", "structGaussianStreamingTypes_1_1BudgetState.html", "structGaussianStreamingTypes_1_1BudgetState" ],
      [ "ChunkLayoutHint", "structGaussianStreamingTypes_1_1ChunkLayoutHint.html", "structGaussianStreamingTypes_1_1ChunkLayoutHint" ],
      [ "ConfigOverrides", "structGaussianStreamingTypes_1_1ConfigOverrides.html", "structGaussianStreamingTypes_1_1ConfigOverrides" ],
      [ "DiagnosticsState", "structGaussianStreamingTypes_1_1DiagnosticsState.html", "structGaussianStreamingTypes_1_1DiagnosticsState" ],
      [ "FrameData", "structGaussianStreamingTypes_1_1FrameData.html", "structGaussianStreamingTypes_1_1FrameData" ],
      [ "PrimaryChunkLayoutMetrics", "structGaussianStreamingTypes_1_1PrimaryChunkLayoutMetrics.html", "structGaussianStreamingTypes_1_1PrimaryChunkLayoutMetrics" ],
      [ "RequestedChunkState", "structGaussianStreamingTypes_1_1RequestedChunkState.html", "structGaussianStreamingTypes_1_1RequestedChunkState" ],
      [ "SchedulerState", "structGaussianStreamingTypes_1_1SchedulerState.html", "structGaussianStreamingTypes_1_1SchedulerState" ],
      [ "StreamingChunk", "structGaussianStreamingTypes_1_1StreamingChunk.html", "structGaussianStreamingTypes_1_1StreamingChunk" ]
    ] ],
    [ "gs", "namespacegs.html", [
      [ "settings", "namespacegs_1_1settings.html", [
        [ "GSLightingSettings", "structgs_1_1settings_1_1GSLightingSettings.html", "structgs_1_1settings_1_1GSLightingSettings" ],
        [ "GSSphereEffectorSettings", "structgs_1_1settings_1_1GSSphereEffectorSettings.html", "structgs_1_1settings_1_1GSSphereEffectorSettings" ],
        [ "GSWindSettings", "structgs_1_1settings_1_1GSWindSettings.html", "structgs_1_1settings_1_1GSWindSettings" ]
      ] ],
      [ "ModuleStringNames", "structgs_1_1ModuleStringNames.html", "structgs_1_1ModuleStringNames" ]
    ] ],
    [ "gs_layout_hint", "namespacegs__layout__hint.html", [
      [ "LayoutHintFailureCounters", "structgs__layout__hint_1_1LayoutHintFailureCounters.html", "structgs__layout__hint_1_1LayoutHintFailureCounters" ],
      [ "LayoutHintFailureState", "structgs__layout__hint_1_1LayoutHintFailureState.html", "structgs__layout__hint_1_1LayoutHintFailureState" ],
      [ "LayoutHintIndexRange", "structgs__layout__hint_1_1LayoutHintIndexRange.html", "structgs__layout__hint_1_1LayoutHintIndexRange" ],
      [ "LayoutHintValidationFailure", "structgs__layout__hint_1_1LayoutHintValidationFailure.html", "structgs__layout__hint_1_1LayoutHintValidationFailure" ]
    ] ],
    [ "gs_sort_policy", "namespacegs__sort__policy.html", [
      [ "ReadbackPolicy", "structgs__sort__policy_1_1ReadbackPolicy.html", "structgs__sort__policy_1_1ReadbackPolicy" ]
    ] ],
    [ "gs_tier_cap", "namespacegs__tier__cap.html", [
      [ "StreamingTierCapPolicy", "structgs__tier__cap_1_1StreamingTierCapPolicy.html", "structgs__tier__cap_1_1StreamingTierCapPolicy" ]
    ] ],
    [ "ResidentAtlasBudget", "namespaceResidentAtlasBudget.html", [
      [ "SubsetPlan", "structResidentAtlasBudget_1_1SubsetPlan.html", "structResidentAtlasBudget_1_1SubsetPlan" ]
    ] ],
    [ "TileShaderCompilation", "namespaceTileShaderCompilation.html", [
      [ "CompilationResult", "structTileShaderCompilation_1_1CompilationResult.html", "structTileShaderCompilation_1_1CompilationResult" ],
      [ "ShaderVariant", "structTileShaderCompilation_1_1ShaderVariant.html", "structTileShaderCompilation_1_1ShaderVariant" ]
    ] ],
    [ "_GSAtomicNoRenameGuard", "struct__GSAtomicNoRenameGuard.html", "struct__GSAtomicNoRenameGuard" ],
    [ "AlgorithmProbe", "structAlgorithmProbe.html", "structAlgorithmProbe" ],
    [ "AssetChunkIndexGPU", "structAssetChunkIndexGPU.html", "structAssetChunkIndexGPU" ],
    [ "AssetDependencyManager", "classAssetDependencyManager.html", "classAssetDependencyManager" ],
    [ "AssetID", "structAssetID.html", "structAssetID" ],
    [ "AssetIDHasher", "structAssetIDHasher.html", null ],
    [ "AssetLodRangeGPU", "structAssetLodRangeGPU.html", "structAssetLodRangeGPU" ],
    [ "AssetMetadata", "structAssetMetadata.html", "structAssetMetadata" ],
    [ "AssetMetaGPU", "structAssetMetaGPU.html", "structAssetMetaGPU" ],
    [ "AttachmentValidationInfo", "structAttachmentValidationInfo.html", "structAttachmentValidationInfo" ],
    [ "AutoTuneResult", "structAutoTuneResult.html", "structAutoTuneResult" ],
    [ "BatchedAsyncReadback", "classBatchedAsyncReadback.html", "classBatchedAsyncReadback" ],
    [ "BitonicSort", "classBitonicSort.html", "classBitonicSort" ],
    [ "ChunkBounds", "structChunkBounds.html", "structChunkBounds" ],
    [ "ChunkLODMetadata", "structChunkLODMetadata.html", "structChunkLODMetadata" ],
    [ "ChunkMetaGPU", "structChunkMetaGPU.html", "structChunkMetaGPU" ],
    [ "ChunkPayloadSource", "classChunkPayloadSource.html", "classChunkPayloadSource" ],
    [ "ChunkQuantizationGPU", "structChunkQuantizationGPU.html", "structChunkQuantizationGPU" ],
    [ "ChunkQuantizationInfo", "structChunkQuantizationInfo.html", "structChunkQuantizationInfo" ],
    [ "ChunkQuantizationRuntimeParams", "structChunkQuantizationRuntimeParams.html", "structChunkQuantizationRuntimeParams" ],
    [ "ChunkSpatialGrid", "structChunkSpatialGrid.html", "structChunkSpatialGrid" ],
    [ "CoarseSyncPolicy", "classCoarseSyncPolicy.html", "classCoarseSyncPolicy" ],
    [ "ColorGradingResource", "classColorGradingResource.html", "classColorGradingResource" ],
    [ "ComputeCapabilityProbe", "structComputeCapabilityProbe.html", "structComputeCapabilityProbe" ],
    [ "CullCounters", "structCullCounters.html", "structCullCounters" ],
    [ "CullInputBuffers", "structCullInputBuffers.html", "structCullInputBuffers" ],
    [ "CullParams", "structCullParams.html", "structCullParams" ],
    [ "CullResult", "structCullResult.html", "structCullResult" ],
    [ "DebugCounterSnapshot", "structDebugCounterSnapshot.html", "structDebugCounterSnapshot" ],
    [ "DebugOverlayCommandSink", "classDebugOverlayCommandSink.html", "classDebugOverlayCommandSink" ],
    [ "DebugOverlayOptions", "structDebugOverlayOptions.html", "structDebugOverlayOptions" ],
    [ "DebugOverlayQueryView", "classDebugOverlayQueryView.html", "classDebugOverlayQueryView" ],
    [ "DebugOverlaySystem", "classDebugOverlaySystem.html", "classDebugOverlaySystem" ],
    [ "DependencyNode", "structDependencyNode.html", "structDependencyNode" ],
    [ "DeviceContext", "structDeviceContext.html", "structDeviceContext" ],
    [ "FramebufferCopyParams", "structFramebufferCopyParams.html", "structFramebufferCopyParams" ],
    [ "FrameCompletionTracker", "classFrameCompletionTracker.html", "classFrameCompletionTracker" ],
    [ "FrustumCullParamsGPU", "structFrustumCullParamsGPU.html", "structFrustumCullParamsGPU" ],
    [ "Gaussian", "structGaussian.html", "structGaussian" ],
    [ "GaussianAtlasAllocator", "classGaussianAtlasAllocator.html", "classGaussianAtlasAllocator" ],
    [ "GaussianData", "classGaussianData.html", "classGaussianData" ],
    [ "GaussianDataLoadResult", "structGaussianDataLoadResult.html", "structGaussianDataLoadResult" ],
    [ "GaussianImportPresetDefinition", "structGaussianImportPresetDefinition.html", "structGaussianImportPresetDefinition" ],
    [ "GaussianMemoryStream", "classGaussianMemoryStream.html", "classGaussianMemoryStream" ],
    [ "GaussianRenderingDiagnostics", "classGaussianRenderingDiagnostics.html", "classGaussianRenderingDiagnostics" ],
    [ "GaussianSplatAsset", "classGaussianSplatAsset.html", "classGaussianSplatAsset" ],
    [ "GaussianSplatConfigRegistry", "classGaussianSplatConfigRegistry.html", null ],
    [ "GaussianSplatContainer", "classGaussianSplatContainer.html", "classGaussianSplatContainer" ],
    [ "GaussianSplatDebugHUD", "classGaussianSplatDebugHUD.html", "classGaussianSplatDebugHUD" ],
    [ "GaussianSplatDynamicInstance3D", "classGaussianSplatDynamicInstance3D.html", "classGaussianSplatDynamicInstance3D" ],
    [ "GaussianSplatManager", "classGaussianSplatManager.html", "classGaussianSplatManager" ],
    [ "GaussianSplatMergeResult", "structGaussianSplatMergeResult.html", "structGaussianSplatMergeResult" ],
    [ "GaussianSplatMergeSource", "structGaussianSplatMergeSource.html", "structGaussianSplatMergeSource" ],
    [ "GaussianSplatNode3D", "classGaussianSplatNode3D.html", "classGaussianSplatNode3D" ],
    [ "GaussianSplatNodeAssetHelper", "classGaussianSplatNodeAssetHelper.html", "classGaussianSplatNodeAssetHelper" ],
    [ "GaussianSplatNodeDebugHelper", "classGaussianSplatNodeDebugHelper.html", "classGaussianSplatNodeDebugHelper" ],
    [ "GaussianSplatNodeQualityHelper", "classGaussianSplatNodeQualityHelper.html", "classGaussianSplatNodeQualityHelper" ],
    [ "GaussianSplatNodeRendererHelper", "classGaussianSplatNodeRendererHelper.html", "classGaussianSplatNodeRendererHelper" ],
    [ "GaussianSplatNodeViewportHelper", "classGaussianSplatNodeViewportHelper.html", "classGaussianSplatNodeViewportHelper" ],
    [ "GaussianSplatNodeVisibilityHelper", "classGaussianSplatNodeVisibilityHelper.html", "classGaussianSplatNodeVisibilityHelper" ],
    [ "GaussianSplatRenderer", "classGaussianSplatRenderer.html", "classGaussianSplatRenderer" ],
    [ "GaussianSplatSceneDirector", "classGaussianSplatSceneDirector.html", "classGaussianSplatSceneDirector" ],
    [ "GaussianSplatSettingsManager", "classGaussianSplatSettingsManager.html", "classGaussianSplatSettingsManager" ],
    [ "GaussianSplattingPerformanceMonitors", "classGaussianSplattingPerformanceMonitors.html", "classGaussianSplattingPerformanceMonitors" ],
    [ "GaussianSplatWorld", "classGaussianSplatWorld.html", "classGaussianSplatWorld" ],
    [ "GaussianSplatWorld3D", "classGaussianSplatWorld3D.html", "classGaussianSplatWorld3D" ],
    [ "GaussianStreamingSystem", "classGaussianStreamingSystem.html", "classGaussianStreamingSystem" ],
    [ "GlobalAtlasState", "structGlobalAtlasState.html", "structGlobalAtlasState" ],
    [ "GPUBuffer", "classGPUBuffer.html", "classGPUBuffer" ],
    [ "GPUBufferManager", "classGPUBufferManager.html", "classGPUBufferManager" ],
    [ "GPUCuller", "classGPUCuller.html", "classGPUCuller" ],
    [ "GPUPerformanceMonitor", "classGPUPerformanceMonitor.html", "classGPUPerformanceMonitor" ],
    [ "GPUSorterFactory", "classGPUSorterFactory.html", "classGPUSorterFactory" ],
    [ "GPUSortingConfig", "structGPUSortingConfig.html", "structGPUSortingConfig" ],
    [ "GPUSortingPipeline", "classGPUSortingPipeline.html", "classGPUSortingPipeline" ],
    [ "GSSceneDepthLinearize", "structGSSceneDepthLinearize.html", "structGSSceneDepthLinearize" ],
    [ "GSStartupTrace", "classGSStartupTrace.html", "classGSStartupTrace" ],
    [ "GSStartupTraceScope", "classGSStartupTraceScope.html", "classGSStartupTraceScope" ],
    [ "GSStartupTraceSnapshot", "structGSStartupTraceSnapshot.html", "structGSStartupTraceSnapshot" ],
    [ "ICuller", "classICuller.html", "classICuller" ],
    [ "IDebugOverlaySystem", "classIDebugOverlaySystem.html", "classIDebugOverlaySystem" ],
    [ "IGaussianLoader", "classIGaussianLoader.html", "classIGaussianLoader" ],
    [ "IGPUSorter", "classIGPUSorter.html", "classIGPUSorter" ],
    [ "IGPUSortingPipeline", "classIGPUSortingPipeline.html", "classIGPUSortingPipeline" ],
    [ "IHierarchicalCuller", "classIHierarchicalCuller.html", "classIHierarchicalCuller" ],
    [ "IInteractiveStateManager", "classIInteractiveStateManager.html", "classIInteractiveStateManager" ],
    [ "InMemoryChunkPayloadSource", "classInMemoryChunkPayloadSource.html", "classInMemoryChunkPayloadSource" ],
    [ "InstanceAssetRegistration", "structInstanceAssetRegistration.html", "structInstanceAssetRegistration" ],
    [ "InstanceCullParamsGPU", "structInstanceCullParamsGPU.html", "structInstanceCullParamsGPU" ],
    [ "InstanceDataGPU", "structInstanceDataGPU.html", "structInstanceDataGPU" ],
    [ "InstanceDepthParamsGPU", "structInstanceDepthParamsGPU.html", "structInstanceDepthParamsGPU" ],
    [ "InstanceGradingGPU", "structInstanceGradingGPU.html", "structInstanceGradingGPU" ],
    [ "InteractiveStateManager", "classInteractiveStateManager.html", "classInteractiveStateManager" ],
    [ "InteractiveUniformData", "structInteractiveUniformData.html", "structInteractiveUniformData" ],
    [ "IOutputCompositor", "classIOutputCompositor.html", "classIOutputCompositor" ],
    [ "IOverflowAutoTuner", "classIOverflowAutoTuner.html", "classIOverflowAutoTuner" ],
    [ "IPainterlyMaterialManager", "classIPainterlyMaterialManager.html", "classIPainterlyMaterialManager" ],
    [ "IPainterlyRenderer", "classIPainterlyRenderer.html", "classIPainterlyRenderer" ],
    [ "IRasterizer", "classIRasterizer.html", "classIRasterizer" ],
    [ "IRenderDeviceManager", "classIRenderDeviceManager.html", "classIRenderDeviceManager" ],
    [ "IRenderer", "classIRenderer.html", "classIRenderer" ],
    [ "IRendererConfig", "classIRendererConfig.html", "classIRendererConfig" ],
    [ "IRendererDebug", "classIRendererDebug.html", "classIRendererDebug" ],
    [ "IRendererLifecycle", "classIRendererLifecycle.html", "classIRendererLifecycle" ],
    [ "IRendererPipeline", "classIRendererPipeline.html", "classIRendererPipeline" ],
    [ "IRendererProvider", "classIRendererProvider.html", "classIRendererProvider" ],
    [ "IRenderThreadDispatcher", "classIRenderThreadDispatcher.html", "classIRenderThreadDispatcher" ],
    [ "ISortBufferHostContext", "classISortBufferHostContext.html", "classISortBufferHostContext" ],
    [ "ISortResultSink", "classISortResultSink.html", "classISortResultSink" ],
    [ "ISyncPolicy", "classISyncPolicy.html", "classISyncPolicy" ],
    [ "LastSortGpuTimestamp", "structLastSortGpuTimestamp.html", "structLastSortGpuTimestamp" ],
    [ "LODBlendConfig", "structLODBlendConfig.html", "structLODBlendConfig" ],
    [ "LODConfig", "structLODConfig.html", "structLODConfig" ],
    [ "LODDebugStats", "structLODDebugStats.html", "structLODDebugStats" ],
    [ "OneSweepSort", "classOneSweepSort.html", "classOneSweepSort" ],
    [ "OutputCompositor", "classOutputCompositor.html", "classOutputCompositor" ],
    [ "OutputCopyParams", "structOutputCopyParams.html", "structOutputCopyParams" ],
    [ "OutputCopyResult", "structOutputCopyResult.html", "structOutputCopyResult" ],
    [ "OverflowAutoTuneConfig", "structOverflowAutoTuneConfig.html", "structOverflowAutoTuneConfig" ],
    [ "OverflowAutoTuner", "classOverflowAutoTuner.html", "classOverflowAutoTuner" ],
    [ "OwnerMismatchRemediationResult", "structOwnerMismatchRemediationResult.html", "structOwnerMismatchRemediationResult" ],
    [ "PackedGaussian", "structPackedGaussian.html", "structPackedGaussian" ],
    [ "PackedGaussianQuantized", "structPackedGaussianQuantized.html", "structPackedGaussianQuantized" ],
    [ "PackedSphericalHarmonics", "structPackedSphericalHarmonics.html", "structPackedSphericalHarmonics" ],
    [ "PainterlyConfig", "structPainterlyConfig.html", "structPainterlyConfig" ],
    [ "PainterlyMaterial", "classPainterlyMaterial.html", "classPainterlyMaterial" ],
    [ "PainterlyMaterialManager", "classPainterlyMaterialManager.html", "classPainterlyMaterialManager" ],
    [ "PainterlyMaterialResources", "structPainterlyMaterialResources.html", "structPainterlyMaterialResources" ],
    [ "PainterlyPassGraph", "classPainterlyPassGraph.html", "classPainterlyPassGraph" ],
    [ "PainterlyPerformance", "structPainterlyPerformance.html", "structPainterlyPerformance" ],
    [ "PainterlyRenderer", "classPainterlyRenderer.html", "classPainterlyRenderer" ],
    [ "PainterlyRenderInput", "structPainterlyRenderInput.html", "structPainterlyRenderInput" ],
    [ "PainterlyRenderResult", "structPainterlyRenderResult.html", "structPainterlyRenderResult" ],
    [ "PainterlyTextureInfo", "structPainterlyTextureInfo.html", "structPainterlyTextureInfo" ],
    [ "PickParams", "structPickParams.html", "structPickParams" ],
    [ "PickResult", "structPickResult.html", "structPickResult" ],
    [ "PipelineFeatureSet", "structPipelineFeatureSet.html", "structPipelineFeatureSet" ],
    [ "PLYLoader", "classPLYLoader.html", "classPLYLoader" ],
    [ "QualityTierConfig", "structQualityTierConfig.html", "structQualityTierConfig" ],
    [ "QuantizationChunkGPU", "structQuantizationChunkGPU.html", "structQuantizationChunkGPU" ],
    [ "QuantizationConfig", "structQuantizationConfig.html", "structQuantizationConfig" ],
    [ "RadixSort", "classRadixSort.html", "classRadixSort" ],
    [ "RasterDebugCounters", "structRasterDebugCounters.html", "structRasterDebugCounters" ],
    [ "RasterDebugOptions", "structRasterDebugOptions.html", "structRasterDebugOptions" ],
    [ "RasterOverflowStats", "structRasterOverflowStats.html", "structRasterOverflowStats" ],
    [ "RasterParams", "structRasterParams.html", "structRasterParams" ],
    [ "RasterPerformance", "structRasterPerformance.html", "structRasterPerformance" ],
    [ "RasterResult", "structRasterResult.html", "structRasterResult" ],
    [ "RasterStats", "structRasterStats.html", "structRasterStats" ],
    [ "RenderConfigOrchestrator", "classRenderConfigOrchestrator.html", "classRenderConfigOrchestrator" ],
    [ "RenderDataOrchestrator", "classRenderDataOrchestrator.html", "classRenderDataOrchestrator" ],
    [ "RenderDebugStateOrchestrator", "classRenderDebugStateOrchestrator.html", "classRenderDebugStateOrchestrator" ],
    [ "RenderDeviceManager", "classRenderDeviceManager.html", "classRenderDeviceManager" ],
    [ "RenderDeviceOrchestrator", "classRenderDeviceOrchestrator.html", "classRenderDeviceOrchestrator" ],
    [ "RenderDiagnosticsOrchestrator", "classRenderDiagnosticsOrchestrator.html", "classRenderDiagnosticsOrchestrator" ],
    [ "RenderFrameContextManager", "classRenderFrameContextManager.html", "classRenderFrameContextManager" ],
    [ "RenderingError", "classRenderingError.html", "classRenderingError" ],
    [ "RenderInstancingOrchestrator", "classRenderInstancingOrchestrator.html", "classRenderInstancingOrchestrator" ],
    [ "RenderOutputOrchestrator", "classRenderOutputOrchestrator.html", "classRenderOutputOrchestrator" ],
    [ "RenderPipelineStages", "classRenderPipelineStages.html", "classRenderPipelineStages" ],
    [ "RenderQualityOrchestrator", "classRenderQualityOrchestrator.html", "classRenderQualityOrchestrator" ],
    [ "RenderResourceOrchestrator", "classRenderResourceOrchestrator.html", "classRenderResourceOrchestrator" ],
    [ "RenderRouteUID", "structRenderRouteUID.html", null ],
    [ "RenderSortingOrchestrator", "classRenderSortingOrchestrator.html", "classRenderSortingOrchestrator" ],
    [ "RenderStreamingOrchestrator", "classRenderStreamingOrchestrator.html", "classRenderStreamingOrchestrator" ],
    [ "RenderStreamingOrchestratorDependencies", "structRenderStreamingOrchestratorDependencies.html", "structRenderStreamingOrchestratorDependencies" ],
    [ "RenderThreadDispatcher", "classRenderThreadDispatcher.html", "classRenderThreadDispatcher" ],
    [ "ResidencyBudgetController", "classResidencyBudgetController.html", "classResidencyBudgetController" ],
    [ "ResourceFormatLoaderGaussianSplat", "classResourceFormatLoaderGaussianSplat.html", "classResourceFormatLoaderGaussianSplat" ],
    [ "ResourceFormatLoaderGaussianSplatWorld", "classResourceFormatLoaderGaussianSplatWorld.html", "classResourceFormatLoaderGaussianSplatWorld" ],
    [ "ResourceFormatSaverGaussianSplatWorld", "classResourceFormatSaverGaussianSplatWorld.html", "classResourceFormatSaverGaussianSplatWorld" ],
    [ "ResourceOwnerMismatchContract", "classResourceOwnerMismatchContract.html", "classResourceOwnerMismatchContract" ],
    [ "SelectionState", "structSelectionState.html", "structSelectionState" ],
    [ "ShaderCompilationHelper", "classShaderCompilationHelper.html", null ],
    [ "ShaderCompilationManager", "classShaderCompilationManager.html", "classShaderCompilationManager" ],
    [ "SHCompressionMetrics", "structSHCompressionMetrics.html", "structSHCompressionMetrics" ],
    [ "SHConfig", "structSHConfig.html", "structSHConfig" ],
    [ "SortBufferHandles", "structSortBufferHandles.html", "structSortBufferHandles" ],
    [ "SorterCapabilities", "structSorterCapabilities.html", "structSorterCapabilities" ],
    [ "SortExternalBufferState", "structSortExternalBufferState.html", "structSortExternalBufferState" ],
    [ "SortFrameContext", "structSortFrameContext.html", "structSortFrameContext" ],
    [ "SortingMetrics", "structSortingMetrics.html", "structSortingMetrics" ],
    [ "SortingMetricsCollector", "classSortingMetricsCollector.html", "classSortingMetricsCollector" ],
    [ "SortingStrategyConfig", "structSortingStrategyConfig.html", "structSortingStrategyConfig" ],
    [ "SortKeyConfig", "structSortKeyConfig.html", "structSortKeyConfig" ],
    [ "SortOperationParams", "structSortOperationParams.html", "structSortOperationParams" ],
    [ "SortOperationResult", "structSortOperationResult.html", "structSortOperationResult" ],
    [ "SortPositionInputs", "structSortPositionInputs.html", "structSortPositionInputs" ],
    [ "SortPreflightResult", "structSortPreflightResult.html", "structSortPreflightResult" ],
    [ "SortPublicationPayload", "structSortPublicationPayload.html", "structSortPublicationPayload" ],
    [ "SortRuntimeState", "structSortRuntimeState.html", "structSortRuntimeState" ],
    [ "SortViewContext", "structSortViewContext.html", "structSortViewContext" ],
    [ "SphereEffector3D", "classSphereEffector3D.html", "classSphereEffector3D" ],
    [ "SphereEffectorGPU", "structSphereEffectorGPU.html", "structSphereEffectorGPU" ],
    [ "SPIRVDiskCache", "classSPIRVDiskCache.html", "classSPIRVDiskCache" ],
    [ "SplatRefGPU", "structSplatRefGPU.html", "structSplatRefGPU" ],
    [ "SPZLoader", "classSPZLoader.html", "classSPZLoader" ],
    [ "StagedFileChunkPayloadSource", "classStagedFileChunkPayloadSource.html", "classStagedFileChunkPayloadSource" ],
    [ "StaticChunk", "structStaticChunk.html", "structStaticChunk" ],
    [ "StreamingChunkBakeRecord", "structStreamingChunkBakeRecord.html", "structStreamingChunkBakeRecord" ],
    [ "StreamingEvictionController", "classStreamingEvictionController.html", "classStreamingEvictionController" ],
    [ "StreamingGlobalAtlasRegistry", "classStreamingGlobalAtlasRegistry.html", "classStreamingGlobalAtlasRegistry" ],
    [ "StreamingPipeline", "classStreamingPipeline.html", "classStreamingPipeline" ],
    [ "StreamingQueuePressureController", "classStreamingQueuePressureController.html", "classStreamingQueuePressureController" ],
    [ "StreamingStats", "structStreamingStats.html", "structStreamingStats" ],
    [ "StreamingTelemetryAdapter", "classStreamingTelemetryAdapter.html", "classStreamingTelemetryAdapter" ],
    [ "StreamingUploadPipeline", "classStreamingUploadPipeline.html", "classStreamingUploadPipeline" ],
    [ "StreamingVisibilityController", "classStreamingVisibilityController.html", "classStreamingVisibilityController" ],
    [ "TileAdaptiveController", "structTileAdaptiveController.html", "structTileAdaptiveController" ],
    [ "TileAsyncReadback", "structTileAsyncReadback.html", "structTileAsyncReadback" ],
    [ "TileBinningStage", "structTileBinningStage.html", "structTileBinningStage" ],
    [ "TilePrefixScanStage", "structTilePrefixScanStage.html", "structTilePrefixScanStage" ],
    [ "TileProjectionLayout", "structTileProjectionLayout.html", "structTileProjectionLayout" ],
    [ "TileRasterizer", "classTileRasterizer.html", "classTileRasterizer" ],
    [ "TileRasterizerStage", "structTileRasterizerStage.html", "structTileRasterizerStage" ],
    [ "TileRenderer", "classTileRenderer.html", "classTileRenderer" ],
    [ "TileRendererDebugStats", "structTileRendererDebugStats.html", "structTileRendererDebugStats" ],
    [ "TileRenderParamsBuilder", "structTileRenderParamsBuilder.html", "structTileRenderParamsBuilder" ],
    [ "TileRenderParamsGPU", "structTileRenderParamsGPU.html", "structTileRenderParamsGPU" ],
    [ "TileResolveStage", "structTileResolveStage.html", "structTileResolveStage" ],
    [ "VisibleChunkRefGPU", "structVisibleChunkRefGPU.html", "structVisibleChunkRefGPU" ],
    [ "VRAMBudgetConfig", "structVRAMBudgetConfig.html", "structVRAMBudgetConfig" ],
    [ "VRAMBudgetRegulator", "classVRAMBudgetRegulator.html", "classVRAMBudgetRegulator" ],
    [ "VRAMDebugStats", "structVRAMDebugStats.html", "structVRAMDebugStats" ]
];