var dir_7647312eaffe3fbde22451c27808fddd =
[
    [ "gaussian_data_loader.cpp", "gaussian__data__loader_8cpp.html", "gaussian__data__loader_8cpp" ],
    [ "gaussian_data_loader.h", "gaussian__data__loader_8h.html", "gaussian__data__loader_8h" ],
    [ "gaussian_import_preset.cpp", "gaussian__import__preset_8cpp.html", "gaussian__import__preset_8cpp" ],
    [ "gaussian_import_preset.h", "gaussian__import__preset_8h.html", "gaussian__import__preset_8h" ],
    [ "gaussian_splat_world_io.cpp", "gaussian__splat__world__io_8cpp.html", "gaussian__splat__world__io_8cpp" ],
    [ "gaussian_splat_world_io.h", "gaussian__splat__world__io_8h.html", "gaussian__splat__world__io_8h" ],
    [ "gs_atomic_file_writer.cpp", "gs__atomic__file__writer_8cpp.html", "gs__atomic__file__writer_8cpp" ],
    [ "gs_atomic_file_writer.h", "gs__atomic__file__writer_8h.html", "gs__atomic__file__writer_8h" ],
    [ "i_gaussian_loader.cpp", "i__gaussian__loader_8cpp.html", null ],
    [ "i_gaussian_loader.h", "i__gaussian__loader_8h.html", "i__gaussian__loader_8h" ],
    [ "io_settings_utils.h", "io__settings__utils_8h.html", "io__settings__utils_8h" ],
    [ "ply_loader.cpp", "ply__loader_8cpp.html", null ],
    [ "ply_loader.h", "ply__loader_8h.html", "ply__loader_8h" ],
    [ "resource_importer_gsplatworld.cpp", "resource__importer__gsplatworld_8cpp.html", null ],
    [ "resource_importer_gsplatworld.h", "resource__importer__gsplatworld_8h.html", null ],
    [ "resource_importer_ply.cpp", "resource__importer__ply_8cpp.html", null ],
    [ "resource_importer_ply.h", "resource__importer__ply_8h.html", null ],
    [ "resource_importer_spz.cpp", "resource__importer__spz_8cpp.html", null ],
    [ "resource_importer_spz.h", "resource__importer__spz_8h.html", null ],
    [ "spz_loader.cpp", "spz__loader_8cpp.html", null ],
    [ "spz_loader.h", "spz__loader_8h.html", "spz__loader_8h" ],
    [ "streaming_chunk_bake.cpp", "streaming__chunk__bake_8cpp.html", "streaming__chunk__bake_8cpp" ],
    [ "streaming_chunk_bake.h", "streaming__chunk__bake_8h.html", "streaming__chunk__bake_8h" ]
];