var gaussian__gpu__layout_8h =
[
    [ "SHCompressionMetrics", "structSHCompressionMetrics.html", "structSHCompressionMetrics" ],
    [ "InstanceDataGPU", "structInstanceDataGPU.html", "structInstanceDataGPU" ],
    [ "SphereEffectorGPU", "structSphereEffectorGPU.html", "structSphereEffectorGPU" ],
    [ "InstanceGradingGPU", "structInstanceGradingGPU.html", "structInstanceGradingGPU" ],
    [ "AssetLodRangeGPU", "structAssetLodRangeGPU.html", "structAssetLodRangeGPU" ],
    [ "AssetMetaGPU", "structAssetMetaGPU.html", "structAssetMetaGPU" ],
    [ "ChunkMetaGPU", "structChunkMetaGPU.html", "structChunkMetaGPU" ],
    [ "AssetChunkIndexGPU", "structAssetChunkIndexGPU.html", "structAssetChunkIndexGPU" ],
    [ "VisibleChunkRefGPU", "structVisibleChunkRefGPU.html", "structVisibleChunkRefGPU" ],
    [ "SplatRefGPU", "structSplatRefGPU.html", "structSplatRefGPU" ],
    [ "QuantizationChunkGPU", "structQuantizationChunkGPU.html", "structQuantizationChunkGPU" ],
    [ "PackedSphericalHarmonics", "structPackedSphericalHarmonics.html", "structPackedSphericalHarmonics" ],
    [ "PackedGaussian", "structPackedGaussian.html", "structPackedGaussian" ],
    [ "PackedGaussianQuantized", "structPackedGaussianQuantized.html", "structPackedGaussianQuantized" ],
    [ "TileRenderParamsGPU", "structTileRenderParamsGPU.html", "structTileRenderParamsGPU" ],
    [ "FrustumCullParamsGPU", "structFrustumCullParamsGPU.html", "structFrustumCullParamsGPU" ],
    [ "InstanceCullParamsGPU", "structInstanceCullParamsGPU.html", "structInstanceCullParamsGPU" ],
    [ "InstanceDepthParamsGPU", "structInstanceDepthParamsGPU.html", "structInstanceDepthParamsGPU" ],
    [ "gs_decode_sh_snorm10", "gaussian__gpu__layout_8h.html#acee1a3ddfa10667f59a7e5d841633b49", null ],
    [ "gs_get_dc_encoding", "gaussian__gpu__layout_8h.html#a5e0979d8b4f165fb9b982aece4ecc375", null ],
    [ "gs_get_sh_encoding", "gaussian__gpu__layout_8h.html#a303f3484b516d598457574be54ec8e02", null ],
    [ "gs_pack_asset_gpu_flags", "gaussian__gpu__layout_8h.html#ac0327edc85af51e286060556c64b5250", null ],
    [ "gs_pack_sh_metadata", "gaussian__gpu__layout_8h.html#a2b6b0a4b03e379b0f72ef504a64967a0", null ],
    [ "pack_gaussian", "gaussian__gpu__layout_8h.html#a178c9cc5e58f97a6568a7805f9552d0d", null ],
    [ "pack_gaussian_quantized", "gaussian__gpu__layout_8h.html#ac7783a87c3628ebab70f184fa1333a10", null ],
    [ "pack_gaussians_range", "gaussian__gpu__layout_8h.html#a649b6fc3d383a141b93b54eba358ff7f", null ],
    [ "pack_gaussians_range_limited", "gaussian__gpu__layout_8h.html#a206bb123d6e2813ddf6b3e3e37d30774", null ],
    [ "pack_gaussians_range_quantized", "gaussian__gpu__layout_8h.html#a48241b4a601e7ae64b8a287981de2a91", null ],
    [ "pack_gaussians_range_raw", "gaussian__gpu__layout_8h.html#a9f669b601043b5af7c8c03071f20da5b", null ],
    [ "pack_gaussians_range_raw", "gaussian__gpu__layout_8h.html#ac893e8915818643b1048aa95d2035297", null ]
];