var hierarchy =
[
    [ "_GSAtomicNoRenameGuard", "struct__GSAtomicNoRenameGuard.html", null ],
    [ "TileRenderer::AdaptiveOverlapBudgetRuntimeState", "structTileRenderer_1_1AdaptiveOverlapBudgetRuntimeState.html", null ],
    [ "TileAdaptiveController::AdaptiveState", "structTileAdaptiveController_1_1AdaptiveState.html", null ],
    [ "ResidencyBudgetController::AdmissionContext", "structResidencyBudgetController_1_1AdmissionContext.html", null ],
    [ "ResidencyBudgetController::AdmissionFrameBudget", "structResidencyBudgetController_1_1AdmissionFrameBudget.html", null ],
    [ "ResidencyBudgetController::AdmissionGate", "structResidencyBudgetController_1_1AdmissionGate.html", null ],
    [ "ResidencyBudgetController::AdmissionPolicy", "structResidencyBudgetController_1_1AdmissionPolicy.html", null ],
    [ "AlgorithmProbe", "structAlgorithmProbe.html", null ],
    [ "GaussianSplatting::AnimationChange", "structGaussianSplatting_1_1AnimationChange.html", null ],
    [ "GaussianSplatting::AnimationClip", "structGaussianSplatting_1_1AnimationClip.html", null ],
    [ "GaussianSplatting::AnimationTrack", "structGaussianSplatting_1_1AnimationTrack.html", null ],
    [ "AssetChunkIndexGPU", "structAssetChunkIndexGPU.html", null ],
    [ "AssetID", "structAssetID.html", null ],
    [ "AssetIDHasher", "structAssetIDHasher.html", null ],
    [ "AssetLodRangeGPU", "structAssetLodRangeGPU.html", null ],
    [ "AssetMetadata", "structAssetMetadata.html", null ],
    [ "AssetMetaGPU", "structAssetMetaGPU.html", null ],
    [ "GaussianSplatting::AssetReference", "structGaussianSplatting_1_1AssetReference.html", null ],
    [ "GaussianStreamingTypes::AssetRegistryState", "structGaussianStreamingTypes_1_1AssetRegistryState.html", null ],
    [ "TileAsyncReadback::AsyncOverflowState", "structTileAsyncReadback_1_1AsyncOverflowState.html", null ],
    [ "TileRendererDebugStats::AsyncReadbackState", "structTileRendererDebugStats_1_1AsyncReadbackState.html", null ],
    [ "TileAsyncReadback::AsyncTileCountsState", "structTileAsyncReadback_1_1AsyncTileCountsState.html", null ],
    [ "GaussianStreamingTypes::AtlasAssetState", "structGaussianStreamingTypes_1_1AtlasAssetState.html", null ],
    [ "AttachmentValidationInfo", "structAttachmentValidationInfo.html", null ],
    [ "GPUSorterFactory::AutoThresholds", "structGPUSorterFactory_1_1AutoThresholds.html", null ],
    [ "AutoTuneResult", "structAutoTuneResult.html", null ],
    [ "TileBinningStage::BinningUniformSets", "structTileBinningStage_1_1BinningUniformSets.html", null ],
    [ "GaussianMemoryStream::MemoryPool::Block", "structGaussianMemoryStream_1_1MemoryPool_1_1Block.html", null ],
    [ "GaussianStreamingTypes::BudgetState", "structGaussianStreamingTypes_1_1BudgetState.html", null ],
    [ "GPUBufferManager::BufferHandle", "structGPUBufferManager_1_1BufferHandle.html", null ],
    [ "GaussianSplatting::BufferOwnership", "structGaussianSplatting_1_1BufferOwnership.html", null ],
    [ "GaussianSplatting::HierarchicalSplatStructure::BuildParams", "structGaussianSplatting_1_1HierarchicalSplatStructure_1_1BuildParams.html", null ],
    [ "OutputCompositor::CachedFramebuffer", "structOutputCompositor_1_1CachedFramebuffer.html", null ],
    [ "StreamingVisibilityController::CameraVelocityTracker", "structStreamingVisibilityController_1_1CameraVelocityTracker.html", null ],
    [ "CanvasLayer", null, [
      [ "GaussianSplatPerformanceOverlay", "classGaussianSplatPerformanceOverlay.html", null ]
    ] ],
    [ "GaussianSplatting::ComputeInfrastructure::CapabilityGatePolicy", "structGaussianSplatting_1_1ComputeInfrastructure_1_1CapabilityGatePolicy.html", null ],
    [ "GaussianSplatting::ChangeEntry", "structGaussianSplatting_1_1ChangeEntry.html", null ],
    [ "ChunkBounds", "structChunkBounds.html", null ],
    [ "StreamingVisibilityController::ChunkCullingStats", "structStreamingVisibilityController_1_1ChunkCullingStats.html", null ],
    [ "GaussianSplatting::ChunkHeader", "structGaussianSplatting_1_1ChunkHeader.html", null ],
    [ "GaussianStreamingTypes::ChunkLayoutHint", "structGaussianStreamingTypes_1_1ChunkLayoutHint.html", null ],
    [ "ChunkLODMetadata", "structChunkLODMetadata.html", null ],
    [ "ChunkMetaGPU", "structChunkMetaGPU.html", null ],
    [ "StreamingGlobalAtlasRegistry::ChunkMetaUploadPlan", "structStreamingGlobalAtlasRegistry_1_1ChunkMetaUploadPlan.html", null ],
    [ "ChunkQuantizationGPU", "structChunkQuantizationGPU.html", null ],
    [ "ChunkQuantizationInfo", "structChunkQuantizationInfo.html", null ],
    [ "ChunkQuantizationRuntimeParams", "structChunkQuantizationRuntimeParams.html", null ],
    [ "ChunkSpatialGrid", "structChunkSpatialGrid.html", null ],
    [ "RenderingError::Code", "structRenderingError_1_1Code.html", null ],
    [ "TileShaderCompilation::CompilationResult", "structTileShaderCompilation_1_1CompilationResult.html", null ],
    [ "RenderPipelineStages::CompositeStage", "structRenderPipelineStages_1_1CompositeStage.html", null ],
    [ "GaussianSplatRenderer::CompositeStageInput", "structGaussianSplatRenderer_1_1CompositeStageInput.html", null ],
    [ "ComputeCapabilityProbe", "structComputeCapabilityProbe.html", null ],
    [ "GaussianStreamingTypes::ConfigOverrides", "structGaussianStreamingTypes_1_1ConfigOverrides.html", null ],
    [ "Control", null, [
      [ "GaussianSplatDebugHUD", "classGaussianSplatDebugHUD.html", null ]
    ] ],
    [ "GaussianRenderFrame::CrossDeviceOperation", "structGaussianRenderFrame_1_1CrossDeviceOperation.html", null ],
    [ "RenderDeviceManager::CrossDeviceOperation", "structRenderDeviceManager_1_1CrossDeviceOperation.html", null ],
    [ "CullCounters", "structCullCounters.html", null ],
    [ "GaussianRenderConfig::CullingConfig", "structGaussianRenderConfig_1_1CullingConfig.html", null ],
    [ "GPUCuller::CullingConfig", "structGPUCuller_1_1CullingConfig.html", null ],
    [ "GPUCuller::CullingInputs", "structGPUCuller_1_1CullingInputs.html", null ],
    [ "GPUCuller::CullingState", "structGPUCuller_1_1CullingState.html", null ],
    [ "GPUCuller::CullingSummary", "structGPUCuller_1_1CullingSummary.html", null ],
    [ "CullInputBuffers", "structCullInputBuffers.html", null ],
    [ "CullParams", "structCullParams.html", null ],
    [ "CullResult", "structCullResult.html", null ],
    [ "RenderPipelineStages::CullStage", "structRenderPipelineStages_1_1CullStage.html", null ],
    [ "GaussianSplatRenderer::CullStageInput", "structGaussianSplatRenderer_1_1CullStageInput.html", null ],
    [ "GaussianRenderState::CullStageOutput", "structGaussianRenderState_1_1CullStageOutput.html", null ],
    [ "GaussianRenderPipeline::DataSourcePlan", "structGaussianRenderPipeline_1_1DataSourcePlan.html", null ],
    [ "GaussianRenderDebug::DebugConfigBase", "structGaussianRenderDebug_1_1DebugConfigBase.html", [
      [ "GaussianRenderDebug::DebugConfig", "structGaussianRenderDebug_1_1DebugConfig.html", null ]
    ] ],
    [ "DebugCounterSnapshot", "structDebugCounterSnapshot.html", null ],
    [ "DebugOverlayCommandSink", "classDebugOverlayCommandSink.html", null ],
    [ "DebugOverlayOptions", "structDebugOverlayOptions.html", null ],
    [ "DebugOverlayQueryView", "classDebugOverlayQueryView.html", null ],
    [ "GaussianSplatSettingsManager::DebugOverlaySettings", "structGaussianSplatSettingsManager_1_1DebugOverlaySettings.html", null ],
    [ "GaussianRenderDebug::DebugState< PreviewModeT, StageMetricsT, PipelineEventT >", "structGaussianRenderDebug_1_1DebugState.html", null ],
    [ "GaussianRenderDebug::DebugState< DebugPreviewMode, StageMetrics, PipelineEvent >", "structGaussianRenderDebug_1_1DebugState.html", null ],
    [ "ResourceOwnerMismatchContract::Decision", "structResourceOwnerMismatchContract_1_1Decision.html", null ],
    [ "GPUBufferManager::DeferredDeletionQueue", "classGPUBufferManager_1_1DeferredDeletionQueue.html", null ],
    [ "GaussianSplatSceneDirector::DeferredRendererWork", "classGaussianSplatSceneDirector_1_1DeferredRendererWork.html", null ],
    [ "RenderConfigOrchestrator::Dependencies", "structRenderConfigOrchestrator_1_1Dependencies.html", null ],
    [ "RenderDataOrchestrator::Dependencies", "structRenderDataOrchestrator_1_1Dependencies.html", null ],
    [ "RenderDebugStateOrchestrator::Dependencies", "structRenderDebugStateOrchestrator_1_1Dependencies.html", null ],
    [ "RenderDiagnosticsOrchestrator::Dependencies", "structRenderDiagnosticsOrchestrator_1_1Dependencies.html", null ],
    [ "RenderInstancingOrchestrator::Dependencies", "structRenderInstancingOrchestrator_1_1Dependencies.html", null ],
    [ "RenderOutputOrchestrator::Dependencies", "structRenderOutputOrchestrator_1_1Dependencies.html", null ],
    [ "RenderQualityOrchestrator::Dependencies", "structRenderQualityOrchestrator_1_1Dependencies.html", null ],
    [ "RenderResourceOrchestrator::Dependencies", "structRenderResourceOrchestrator_1_1Dependencies.html", null ],
    [ "RenderSortingOrchestrator::Dependencies", "structRenderSortingOrchestrator_1_1Dependencies.html", null ],
    [ "DependencyNode", "structDependencyNode.html", null ],
    [ "AssetDependencyManager::DependencyStats", "structAssetDependencyManager_1_1DependencyStats.html", null ],
    [ "DeviceContext", "structDeviceContext.html", null ],
    [ "GaussianRenderFacadeState::DeviceState", "structGaussianRenderFacadeState_1_1DeviceState.html", null ],
    [ "GaussianRenderFrame::DiagnosticsState", "structGaussianRenderFrame_1_1DiagnosticsState.html", null ],
    [ "GaussianStreamingTypes::DiagnosticsState", "structGaussianStreamingTypes_1_1DiagnosticsState.html", null ],
    [ "GaussianRenderFrame::ErrorRecoveryStateMachine", "structGaussianRenderFrame_1_1ErrorRecoveryStateMachine.html", null ],
    [ "GaussianSplatting::ComputeInfrastructure::FallbackDecision", "structGaussianSplatting_1_1ComputeInfrastructure_1_1FallbackDecision.html", null ],
    [ "Float16Utils::Float16ConversionStats", "structFloat16Utils_1_1Float16ConversionStats.html", null ],
    [ "GaussianSplatRenderer::FrameBackendPlan", "structGaussianSplatRenderer_1_1FrameBackendPlan.html", null ],
    [ "FramebufferCopyParams", "structFramebufferCopyParams.html", null ],
    [ "OutputCompositor::FramebufferValidationCacheEntry", "structOutputCompositor_1_1FramebufferValidationCacheEntry.html", null ],
    [ "GaussianSplatPerformanceOverlay::FrameClock", "structGaussianSplatPerformanceOverlay_1_1FrameClock.html", null ],
    [ "FrameCompletionTracker", "classFrameCompletionTracker.html", null ],
    [ "GaussianStreamingTypes::FrameData", "structGaussianStreamingTypes_1_1FrameData.html", null ],
    [ "GaussianSplatRenderer::RenderFrameContext::FrameDeps", "structGaussianSplatRenderer_1_1RenderFrameContext_1_1FrameDeps.html", null ],
    [ "GPUPerformanceMonitor::FrameMetrics", "structGPUPerformanceMonitor_1_1FrameMetrics.html", null ],
    [ "RenderFrameContextManager::FrameState", "structRenderFrameContextManager_1_1FrameState.html", null ],
    [ "GaussianRenderFrame::FrameTimingSample", "structGaussianRenderFrame_1_1FrameTimingSample.html", null ],
    [ "FrustumCullParamsGPU", "structFrustumCullParamsGPU.html", null ],
    [ "Gaussian", "structGaussian.html", null ],
    [ "GaussianAtlasAllocator", "classGaussianAtlasAllocator.html", null ],
    [ "GaussianSplatting::GaussianData", "structGaussianSplatting_1_1GaussianData.html", null ],
    [ "GaussianDataLoadResult", "structGaussianDataLoadResult.html", null ],
    [ "GaussianImportPresetDefinition", "structGaussianImportPresetDefinition.html", null ],
    [ "GaussianRenderingDiagnostics", "classGaussianRenderingDiagnostics.html", null ],
    [ "GaussianSplatConfigRegistry", "classGaussianSplatConfigRegistry.html", null ],
    [ "GaussianSplatting::GaussianSplatLODConfig", "structGaussianSplatting_1_1GaussianSplatLODConfig.html", null ],
    [ "GaussianSplatMergeResult", "structGaussianSplatMergeResult.html", null ],
    [ "GaussianSplatMergeSource", "structGaussianSplatMergeSource.html", null ],
    [ "GaussianSplatNodeAssetHelper", "classGaussianSplatNodeAssetHelper.html", null ],
    [ "GaussianSplatNodeDebugHelper", "classGaussianSplatNodeDebugHelper.html", null ],
    [ "GaussianSplatNodeQualityHelper", "classGaussianSplatNodeQualityHelper.html", null ],
    [ "GaussianSplatNodeRendererHelper", "classGaussianSplatNodeRendererHelper.html", null ],
    [ "GaussianSplatNodeViewportHelper", "classGaussianSplatNodeViewportHelper.html", null ],
    [ "GaussianSplatNodeVisibilityHelper", "classGaussianSplatNodeVisibilityHelper.html", null ],
    [ "GaussianSplatSettingsManager", "classGaussianSplatSettingsManager.html", null ],
    [ "GaussianSplatting::GaussianSplatStreamingConfig", "structGaussianSplatting_1_1GaussianSplatStreamingConfig.html", null ],
    [ "GlobalAtlasState", "structGlobalAtlasState.html", null ],
    [ "GPUBuffer", "classGPUBuffer.html", null ],
    [ "GPUPerformanceMonitor", "classGPUPerformanceMonitor.html", null ],
    [ "GPUSorterFactory", "classGPUSorterFactory.html", null ],
    [ "GPUSortingConfig", "structGPUSortingConfig.html", null ],
    [ "gs::settings::GSLightingSettings", "structgs_1_1settings_1_1GSLightingSettings.html", null ],
    [ "GSSceneDepthLinearize", "structGSSceneDepthLinearize.html", null ],
    [ "gs::settings::GSSphereEffectorSettings", "structgs_1_1settings_1_1GSSphereEffectorSettings.html", null ],
    [ "GSStartupTrace", "classGSStartupTrace.html", null ],
    [ "GSStartupTraceScope", "classGSStartupTraceScope.html", null ],
    [ "GSStartupTraceSnapshot", "structGSStartupTraceSnapshot.html", null ],
    [ "gs::settings::GSWindSettings", "structgs_1_1settings_1_1GSWindSettings.html", null ],
    [ "GaussianSplatting::HierarchicalSplatStructure", "classGaussianSplatting_1_1HierarchicalSplatStructure.html", null ],
    [ "ICuller", "classICuller.html", [
      [ "GPUCuller", "classGPUCuller.html", null ],
      [ "IHierarchicalCuller", "classIHierarchicalCuller.html", null ]
    ] ],
    [ "IDebugOverlaySystem", "classIDebugOverlaySystem.html", [
      [ "DebugOverlaySystem", "classDebugOverlaySystem.html", null ]
    ] ],
    [ "GaussianSplatRenderer::IFrameMutationAccess", "classGaussianSplatRenderer_1_1IFrameMutationAccess.html", [
      [ "GaussianSplatRenderer::FrameStateProvider", "classGaussianSplatRenderer_1_1FrameStateProvider.html", null ]
    ] ],
    [ "GaussianSplatRenderer::IFrameStateView", "classGaussianSplatRenderer_1_1IFrameStateView.html", [
      [ "GaussianSplatRenderer::FrameStateProvider", "classGaussianSplatRenderer_1_1FrameStateProvider.html", null ]
    ] ],
    [ "IGPUSortingPipeline", "classIGPUSortingPipeline.html", [
      [ "GPUSortingPipeline", "classGPUSortingPipeline.html", null ]
    ] ],
    [ "IInteractiveStateManager", "classIInteractiveStateManager.html", [
      [ "InteractiveStateManager", "classInteractiveStateManager.html", null ]
    ] ],
    [ "GaussianSplatting::IndirectDispatchLayout", "structGaussianSplatting_1_1IndirectDispatchLayout.html", null ],
    [ "ResourceOwnerMismatchContract::Inputs", "structResourceOwnerMismatchContract_1_1Inputs.html", null ],
    [ "InstanceAssetRegistration", "structInstanceAssetRegistration.html", null ],
    [ "InstanceCullParamsGPU", "structInstanceCullParamsGPU.html", null ],
    [ "InstanceDataGPU", "structInstanceDataGPU.html", null ],
    [ "InstanceDepthParamsGPU", "structInstanceDepthParamsGPU.html", null ],
    [ "InstanceGradingGPU", "structInstanceGradingGPU.html", null ],
    [ "GaussianRenderPipeline::InstancePipelineBuffers", "structGaussianRenderPipeline_1_1InstancePipelineBuffers.html", null ],
    [ "GPUCuller::InstancePipelineInputs", "structGPUCuller_1_1InstancePipelineInputs.html", null ],
    [ "GPUSortingPipeline::InstancePipelineInputs", "structGPUSortingPipeline_1_1InstancePipelineInputs.html", null ],
    [ "RenderInstancingOrchestrator::InstanceReadinessResult", "structRenderInstancingOrchestrator_1_1InstanceReadinessResult.html", null ],
    [ "GaussianSplatSceneDirector::InstanceSubmission", "structGaussianSplatSceneDirector_1_1InstanceSubmission.html", null ],
    [ "GaussianRenderConfig::InteractiveStateConfig< InteractiveStateT >", "structGaussianRenderConfig_1_1InteractiveStateConfig.html", null ],
    [ "GaussianRenderConfig::InteractiveStateConfig< InteractiveState >", "structGaussianRenderConfig_1_1InteractiveStateConfig.html", null ],
    [ "InteractiveUniformData", "structInteractiveUniformData.html", null ],
    [ "GaussianSplatting::InstancePipelineContract::InvariantViolation", "structGaussianSplatting_1_1InstancePipelineContract_1_1InvariantViolation.html", null ],
    [ "IOutputCompositor", "classIOutputCompositor.html", [
      [ "OutputCompositor", "classOutputCompositor.html", null ]
    ] ],
    [ "IOverflowAutoTuner", "classIOverflowAutoTuner.html", [
      [ "OverflowAutoTuner", "classOverflowAutoTuner.html", null ]
    ] ],
    [ "IPainterlyMaterialManager", "classIPainterlyMaterialManager.html", [
      [ "PainterlyMaterialManager", "classPainterlyMaterialManager.html", null ]
    ] ],
    [ "IPainterlyRenderer", "classIPainterlyRenderer.html", [
      [ "PainterlyRenderer", "classPainterlyRenderer.html", null ]
    ] ],
    [ "IRasterizer", "classIRasterizer.html", [
      [ "TileRasterizer", "classTileRasterizer.html", null ]
    ] ],
    [ "IRenderDeviceManager", "classIRenderDeviceManager.html", [
      [ "RenderDeviceManager", "classRenderDeviceManager.html", null ]
    ] ],
    [ "IRendererConfig", "classIRendererConfig.html", [
      [ "IRenderer", "classIRenderer.html", [
        [ "GaussianSplatRenderer", "classGaussianSplatRenderer.html", null ]
      ] ]
    ] ],
    [ "IRendererDebug", "classIRendererDebug.html", [
      [ "IRenderer", "classIRenderer.html", null ]
    ] ],
    [ "IRendererLifecycle", "classIRendererLifecycle.html", [
      [ "IRenderer", "classIRenderer.html", null ]
    ] ],
    [ "IRendererPipeline", "classIRendererPipeline.html", [
      [ "IRenderer", "classIRenderer.html", null ]
    ] ],
    [ "IRendererProvider", "classIRendererProvider.html", null ],
    [ "IRenderThreadDispatcher", "classIRenderThreadDispatcher.html", [
      [ "RenderThreadDispatcher", "classRenderThreadDispatcher.html", [
        [ "GsOverlayStatsDispatcher", "classGsOverlayStatsDispatcher.html", null ]
      ] ]
    ] ],
    [ "ISortBufferHostContext", "classISortBufferHostContext.html", [
      [ "GaussianSplatRenderer", "classGaussianSplatRenderer.html", null ]
    ] ],
    [ "ISortResultSink", "classISortResultSink.html", [
      [ "GaussianSplatRenderer", "classGaussianSplatRenderer.html", null ]
    ] ],
    [ "ISyncPolicy", "classISyncPolicy.html", [
      [ "CoarseSyncPolicy", "classCoarseSyncPolicy.html", null ]
    ] ],
    [ "GaussianRenderDebug::JacobianDebugConfig", "structGaussianRenderDebug_1_1JacobianDebugConfig.html", null ],
    [ "GaussianSplatting::Keyframe", "structGaussianSplatting_1_1Keyframe.html", null ],
    [ "GaussianSplatting::KeyframeInterpolator", "classGaussianSplatting_1_1KeyframeInterpolator.html", null ],
    [ "OutputCompositor::LastCompositeStats", "structOutputCompositor_1_1LastCompositeStats.html", null ],
    [ "LastSortGpuTimestamp", "structLastSortGpuTimestamp.html", null ],
    [ "gs_layout_hint::LayoutHintFailureCounters", "structgs__layout__hint_1_1LayoutHintFailureCounters.html", null ],
    [ "gs_layout_hint::LayoutHintFailureState", "structgs__layout__hint_1_1LayoutHintFailureState.html", null ],
    [ "gs_layout_hint::LayoutHintIndexRange", "structgs__layout__hint_1_1LayoutHintIndexRange.html", null ],
    [ "gs_layout_hint::LayoutHintValidationFailure", "structgs__layout__hint_1_1LayoutHintValidationFailure.html", null ],
    [ "LODBlendConfig", "structLODBlendConfig.html", null ],
    [ "LODConfig", "structLODConfig.html", null ],
    [ "LODDebugStats", "structLODDebugStats.html", null ],
    [ "GaussianSplatting::HierarchicalSplatStructure::QueryResult::LODStats", "structGaussianSplatting_1_1HierarchicalSplatStructure_1_1QueryResult_1_1LODStats.html", null ],
    [ "GaussianMemoryStream::MemoryPool", "structGaussianMemoryStream_1_1MemoryPool.html", null ],
    [ "gs::ModuleStringNames", "structgs_1_1ModuleStringNames.html", null ],
    [ "GaussianSplattingPerformanceMonitors::MonitorSourceInfo", "structGaussianSplattingPerformanceMonitors_1_1MonitorSourceInfo.html", null ],
    [ "GaussianSplatRenderer::MonitorStreamingSnapshot", "structGaussianSplatRenderer_1_1MonitorStreamingSnapshot.html", null ],
    [ "StreamingQueuePressureController::NeededSetProgressInput", "structStreamingQueuePressureController_1_1NeededSetProgressInput.html", null ],
    [ "StreamingQueuePressureController::NeededSetProgressState", "structStreamingQueuePressureController_1_1NeededSetProgressState.html", null ],
    [ "Node3D", null, [
      [ "GaussianSplatContainer", "classGaussianSplatContainer.html", null ],
      [ "GaussianSplatNode3D", "classGaussianSplatNode3D.html", [
        [ "GaussianSplatDynamicInstance3D", "classGaussianSplatDynamicInstance3D.html", null ]
      ] ],
      [ "GaussianSplatWorld3D", "classGaussianSplatWorld3D.html", null ],
      [ "SphereEffector3D", "classSphereEffector3D.html", null ]
    ] ],
    [ "StreamingEvictionController::NonPrimaryEvictionCandidate", "structStreamingEvictionController_1_1NonPrimaryEvictionCandidate.html", null ],
    [ "Object", null, [
      [ "GaussianSplatManager", "classGaussianSplatManager.html", null ],
      [ "GaussianSplatSceneDirector", "classGaussianSplatSceneDirector.html", null ],
      [ "GaussianSplattingPerformanceMonitors", "classGaussianSplattingPerformanceMonitors.html", null ]
    ] ],
    [ "GaussianSplatting::HierarchicalSplatStructure::OctreeNode", "structGaussianSplatting_1_1HierarchicalSplatStructure_1_1OctreeNode.html", null ],
    [ "OutputCompositor::OutputCacheState", "structOutputCompositor_1_1OutputCacheState.html", null ],
    [ "OutputCopyParams", "structOutputCopyParams.html", null ],
    [ "OutputCopyResult", "structOutputCopyResult.html", null ],
    [ "OverflowAutoTuneConfig", "structOverflowAutoTuneConfig.html", null ],
    [ "OwnerMismatchRemediationResult", "structOwnerMismatchRemediationResult.html", null ],
    [ "PackedGaussian", "structPackedGaussian.html", null ],
    [ "PackedGaussianQuantized", "structPackedGaussianQuantized.html", null ],
    [ "TileProjectionLayout::PackedPayload", "structTileProjectionLayout_1_1PackedPayload.html", null ],
    [ "PackedSphericalHarmonics", "structPackedSphericalHarmonics.html", null ],
    [ "StreamingUploadPipeline::PackJob", "structStreamingUploadPipeline_1_1PackJob.html", null ],
    [ "StreamingUploadPipeline::PackSnapshotScratch", "structStreamingUploadPipeline_1_1PackSnapshotScratch.html", null ],
    [ "StreamingUploadPipeline::PackTelemetry", "structStreamingUploadPipeline_1_1PackTelemetry.html", null ],
    [ "StreamingUploadPipeline::PackThreadContext", "structStreamingUploadPipeline_1_1PackThreadContext.html", null ],
    [ "GaussianAtlasAllocator::PageRun", "structGaussianAtlasAllocator_1_1PageRun.html", null ],
    [ "GaussianRenderPipeline::PainterlyCompositePushConstant", "structGaussianRenderPipeline_1_1PainterlyCompositePushConstant.html", null ],
    [ "GaussianRenderConfig::PainterlyConfig", "structGaussianRenderConfig_1_1PainterlyConfig.html", null ],
    [ "PainterlyConfig", "structPainterlyConfig.html", null ],
    [ "GaussianSplatting::PainterlyManager", "classGaussianSplatting_1_1PainterlyManager.html", null ],
    [ "PainterlyMaterialResources", "structPainterlyMaterialResources.html", null ],
    [ "GaussianSplatting::PainterlyMetadata", "structGaussianSplatting_1_1PainterlyMetadata.html", null ],
    [ "PainterlyPassGraph", "classPainterlyPassGraph.html", null ],
    [ "PainterlyPerformance", "structPainterlyPerformance.html", null ],
    [ "PainterlyRenderInput", "structPainterlyRenderInput.html", null ],
    [ "PainterlyRenderResult", "structPainterlyRenderResult.html", null ],
    [ "PainterlyTextureInfo", "structPainterlyTextureInfo.html", null ],
    [ "GaussianSplatting::PassColors", "structGaussianSplatting_1_1PassColors.html", null ],
    [ "PainterlyPassGraph::PassNode", "structPainterlyPassGraph_1_1PassNode.html", null ],
    [ "TileProjectionLayout::Payload", "structTileProjectionLayout_1_1Payload.html", null ],
    [ "GaussianSplatAsset::PayloadSnapshot", "structGaussianSplatAsset_1_1PayloadSnapshot.html", null ],
    [ "StreamingUploadPipeline::PendingChunkUpload", "structStreamingUploadPipeline_1_1PendingChunkUpload.html", null ],
    [ "GaussianRenderPerformance::PerformanceMetrics", "structGaussianRenderPerformance_1_1PerformanceMetrics.html", null ],
    [ "GaussianRenderPerformance::PerformanceSettings", "structGaussianRenderPerformance_1_1PerformanceSettings.html", null ],
    [ "GaussianRenderPerformance::PerformanceState", "structGaussianRenderPerformance_1_1PerformanceState.html", null ],
    [ "PickParams", "structPickParams.html", null ],
    [ "PickResult", "structPickResult.html", null ],
    [ "GaussianRenderPipeline::PipelineEvent", "structGaussianRenderPipeline_1_1PipelineEvent.html", null ],
    [ "PipelineFeatureSet", "structPipelineFeatureSet.html", null ],
    [ "GaussianSplatRenderer::PipelineState", "structGaussianSplatRenderer_1_1PipelineState.html", null ],
    [ "PLYLoader::PLYHeader", "structPLYLoader_1_1PLYHeader.html", null ],
    [ "PLYLoader::PLYProperty", "structPLYLoader_1_1PLYProperty.html", null ],
    [ "GPUSorterFactory::PolicyDecision", "structGPUSorterFactory_1_1PolicyDecision.html", null ],
    [ "GPUSorterFactory::PolicyProbe", "structGPUSorterFactory_1_1PolicyProbe.html", null ],
    [ "TilePrefixScanStage::PrefixDispatchContext", "structTilePrefixScanStage_1_1PrefixDispatchContext.html", null ],
    [ "StreamingQueuePressureController::PressureSample", "structStreamingQueuePressureController_1_1PressureSample.html", null ],
    [ "StreamingQueuePressureController::PressureSummary", "structStreamingQueuePressureController_1_1PressureSummary.html", null ],
    [ "GaussianStreamingTypes::PrimaryChunkLayoutMetrics", "structGaussianStreamingTypes_1_1PrimaryChunkLayoutMetrics.html", null ],
    [ "GaussianRenderPipeline::PublishedInstanceAssetRemap", "structGaussianRenderPipeline_1_1PublishedInstanceAssetRemap.html", null ],
    [ "QualityTierConfig", "structQualityTierConfig.html", null ],
    [ "Float16Utils::QuantizationChunk", "structFloat16Utils_1_1QuantizationChunk.html", null ],
    [ "QuantizationChunkGPU", "structQuantizationChunkGPU.html", null ],
    [ "QuantizationConfig", "structQuantizationConfig.html", null ],
    [ "GaussianSplatting::HierarchicalSplatStructure::QueryResult", "structGaussianSplatting_1_1HierarchicalSplatStructure_1_1QueryResult.html", null ],
    [ "StreamingTelemetryAdapter::QueuePressureSnapshot", "structStreamingTelemetryAdapter_1_1QueuePressureSnapshot.html", null ],
    [ "RenderPipelineStages::RasterCompositeStage", "structRenderPipelineStages_1_1RasterCompositeStage.html", null ],
    [ "RasterDebugCounters", "structRasterDebugCounters.html", null ],
    [ "RasterDebugOptions", "structRasterDebugOptions.html", null ],
    [ "RasterOverflowStats", "structRasterOverflowStats.html", null ],
    [ "RasterParams", "structRasterParams.html", null ],
    [ "RasterPerformance", "structRasterPerformance.html", null ],
    [ "RasterResult", "structRasterResult.html", null ],
    [ "RenderPipelineStages::RasterStage", "structRenderPipelineStages_1_1RasterStage.html", null ],
    [ "GaussianSplatRenderer::RasterStageInput", "structGaussianSplatRenderer_1_1RasterStageInput.html", null ],
    [ "GaussianRenderPipeline::RasterStageOutput", "structGaussianRenderPipeline_1_1RasterStageOutput.html", null ],
    [ "RasterStats", "structRasterStats.html", null ],
    [ "TileRasterizerStage::RasterUniformSets", "structTileRasterizerStage_1_1RasterUniformSets.html", null ],
    [ "gs_sort_policy::ReadbackPolicy", "structgs__sort__policy_1_1ReadbackPolicy.html", null ],
    [ "BatchedAsyncReadback::ReadbackRequest", "structBatchedAsyncReadback_1_1ReadbackRequest.html", null ],
    [ "RefCounted", null, [
      [ "AssetDependencyManager", "classAssetDependencyManager.html", null ],
      [ "BatchedAsyncReadback", "classBatchedAsyncReadback.html", null ],
      [ "ChunkPayloadSource", "classChunkPayloadSource.html", [
        [ "InMemoryChunkPayloadSource", "classInMemoryChunkPayloadSource.html", null ],
        [ "StagedFileChunkPayloadSource", "classStagedFileChunkPayloadSource.html", null ]
      ] ],
      [ "CoarseSyncPolicy", "classCoarseSyncPolicy.html", null ],
      [ "DebugOverlaySystem", "classDebugOverlaySystem.html", null ],
      [ "GPUBufferManager", "classGPUBufferManager.html", null ],
      [ "GPUCuller", "classGPUCuller.html", null ],
      [ "GPUSortingPipeline", "classGPUSortingPipeline.html", null ],
      [ "GaussianMemoryStream", "classGaussianMemoryStream.html", null ],
      [ "GaussianSplatRenderer", "classGaussianSplatRenderer.html", null ],
      [ "GaussianStreamingSystem", "classGaussianStreamingSystem.html", null ],
      [ "IGPUSorter", "classIGPUSorter.html", [
        [ "BitonicSort", "classBitonicSort.html", null ],
        [ "OneSweepSort", "classOneSweepSort.html", null ],
        [ "RadixSort", "classRadixSort.html", null ]
      ] ],
      [ "IGaussianLoader", "classIGaussianLoader.html", null ],
      [ "InteractiveStateManager", "classInteractiveStateManager.html", null ],
      [ "OutputCompositor", "classOutputCompositor.html", null ],
      [ "OverflowAutoTuner", "classOverflowAutoTuner.html", null ],
      [ "PLYLoader", "classPLYLoader.html", null ],
      [ "PainterlyMaterialManager", "classPainterlyMaterialManager.html", null ],
      [ "PainterlyRenderer", "classPainterlyRenderer.html", null ],
      [ "RenderDeviceManager", "classRenderDeviceManager.html", null ],
      [ "SPZLoader", "classSPZLoader.html", null ],
      [ "StreamingPipeline", "classStreamingPipeline.html", null ],
      [ "TileRasterizer", "classTileRasterizer.html", null ],
      [ "TileRenderer", "classTileRenderer.html", null ],
      [ "VRAMBudgetRegulator", "classVRAMBudgetRegulator.html", null ]
    ] ],
    [ "GaussianRenderConfig::RenderConfig< RenderModeT >", "structGaussianRenderConfig_1_1RenderConfig.html", null ],
    [ "GaussianRenderConfig::RenderConfig< RenderMode >", "structGaussianRenderConfig_1_1RenderConfig.html", null ],
    [ "RenderConfigOrchestrator", "classRenderConfigOrchestrator.html", null ],
    [ "RenderDataOrchestrator", "classRenderDataOrchestrator.html", null ],
    [ "RenderDebugStateOrchestrator", "classRenderDebugStateOrchestrator.html", null ],
    [ "RenderDeviceOrchestrator", "classRenderDeviceOrchestrator.html", null ],
    [ "RenderDiagnosticsOrchestrator", "classRenderDiagnosticsOrchestrator.html", null ],
    [ "GaussianSplatSceneDirector::RendererContractWorkQueue", "classGaussianSplatSceneDirector_1_1RendererContractWorkQueue.html", null ],
    [ "GaussianSplatRenderer::RenderFrameContext", "structGaussianSplatRenderer_1_1RenderFrameContext.html", null ],
    [ "RenderFrameContextManager", "classRenderFrameContextManager.html", null ],
    [ "TileRenderer::RenderFrameExecutor", "classTileRenderer_1_1RenderFrameExecutor.html", null ],
    [ "GaussianRenderPipeline::RenderFramePlan", "structGaussianRenderPipeline_1_1RenderFramePlan.html", null ],
    [ "GaussianRenderPipeline::RenderFrameSnapshot", "structGaussianRenderPipeline_1_1RenderFrameSnapshot.html", null ],
    [ "RenderingError", "classRenderingError.html", null ],
    [ "RenderInstancingOrchestrator", "classRenderInstancingOrchestrator.html", null ],
    [ "RenderOutputOrchestrator", "classRenderOutputOrchestrator.html", null ],
    [ "RenderPipelineStages", "classRenderPipelineStages.html", null ],
    [ "RenderQualityOrchestrator", "classRenderQualityOrchestrator.html", null ],
    [ "RenderResourceOrchestrator", "classRenderResourceOrchestrator.html", null ],
    [ "TileRenderer::RenderResult", "structTileRenderer_1_1RenderResult.html", null ],
    [ "GaussianRenderPipeline::RenderRouteDecision", "structGaussianRenderPipeline_1_1RenderRouteDecision.html", null ],
    [ "RenderRouteUID", "structRenderRouteUID.html", null ],
    [ "RenderSortingOrchestrator", "classRenderSortingOrchestrator.html", null ],
    [ "RenderStreamingOrchestrator", "classRenderStreamingOrchestrator.html", null ],
    [ "RenderStreamingOrchestratorDependencies", "structRenderStreamingOrchestratorDependencies.html", null ],
    [ "GaussianSplatPerformanceOverlay::ReportInputs", "structGaussianSplatPerformanceOverlay_1_1ReportInputs.html", null ],
    [ "GaussianStreamingTypes::RequestedChunkState", "structGaussianStreamingTypes_1_1RequestedChunkState.html", null ],
    [ "ResidencyBudgetController", "classResidencyBudgetController.html", null ],
    [ "TileResolveStage::ResolvePushConstants", "structTileResolveStage_1_1ResolvePushConstants.html", null ],
    [ "Resource", null, [
      [ "ColorGradingResource", "classColorGradingResource.html", null ],
      [ "GaussianData", "classGaussianData.html", null ],
      [ "GaussianSplatAsset", "classGaussianSplatAsset.html", null ],
      [ "GaussianSplatWorld", "classGaussianSplatWorld.html", null ],
      [ "GaussianSplatting::GaussianAnimationStateMachine", "classGaussianSplatting_1_1GaussianAnimationStateMachine.html", null ],
      [ "GaussianSplatting::GaussianIncrementalSaver", "classGaussianSplatting_1_1GaussianIncrementalSaver.html", null ],
      [ "GaussianSplatting::GaussianSceneSerializer", "classGaussianSplatting_1_1GaussianSceneSerializer.html", null ],
      [ "PainterlyMaterial", "classPainterlyMaterial.html", null ]
    ] ],
    [ "ResourceFormatLoader", null, [
      [ "ResourceFormatLoaderGaussianSplat", "classResourceFormatLoaderGaussianSplat.html", null ],
      [ "ResourceFormatLoaderGaussianSplatWorld", "classResourceFormatLoaderGaussianSplatWorld.html", null ]
    ] ],
    [ "ResourceFormatSaver", null, [
      [ "ResourceFormatSaverGaussianSplatWorld", "classResourceFormatSaverGaussianSplatWorld.html", null ]
    ] ],
    [ "ResourceOwnerMismatchContract", "classResourceOwnerMismatchContract.html", null ],
    [ "GaussianRenderFacadeState::ResourceState", "structGaussianRenderFacadeState_1_1ResourceState.html", null ],
    [ "GaussianRenderFrame::RuntimeErrorStatistics", "structGaussianRenderFrame_1_1RuntimeErrorStatistics.html", null ],
    [ "GaussianSplatRenderer::RuntimeFidelityPolicy", "structGaussianSplatRenderer_1_1RuntimeFidelityPolicy.html", null ],
    [ "RenderDataOrchestrator::RuntimePorts", "structRenderDataOrchestrator_1_1RuntimePorts.html", null ],
    [ "RenderDebugStateOrchestrator::RuntimePorts", "structRenderDebugStateOrchestrator_1_1RuntimePorts.html", null ],
    [ "RenderDiagnosticsOrchestrator::RuntimePorts", "structRenderDiagnosticsOrchestrator_1_1RuntimePorts.html", null ],
    [ "RenderOutputOrchestrator::RuntimePorts", "structRenderOutputOrchestrator_1_1RuntimePorts.html", null ],
    [ "RenderQualityOrchestrator::RuntimePorts", "structRenderQualityOrchestrator_1_1RuntimePorts.html", null ],
    [ "RenderResourceOrchestrator::RuntimePorts", "structRenderResourceOrchestrator_1_1RuntimePorts.html", null ],
    [ "RenderStreamingOrchestratorDependencies::RuntimePorts", "structRenderStreamingOrchestratorDependencies_1_1RuntimePorts.html", null ],
    [ "StreamingQueuePressureController::ScanBudgetInput", "structStreamingQueuePressureController_1_1ScanBudgetInput.html", null ],
    [ "StreamingQueuePressureController::ScanBudgetResult", "structStreamingQueuePressureController_1_1ScanBudgetResult.html", null ],
    [ "GaussianSplatting::SceneHeader", "structGaussianSplatting_1_1SceneHeader.html", null ],
    [ "GaussianRenderState::SceneState", "structGaussianRenderState_1_1SceneState.html", null ],
    [ "GaussianStreamingTypes::SchedulerState", "structGaussianStreamingTypes_1_1SchedulerState.html", null ],
    [ "GaussianSplatting::ScopedGpuMarker", "classGaussianSplatting_1_1ScopedGpuMarker.html", null ],
    [ "GaussianSplatting::ScopedGpuMarkerEx", "classGaussianSplatting_1_1ScopedGpuMarkerEx.html", null ],
    [ "StagedFileChunkPayloadSource::ScopedReaderSuspend", "classStagedFileChunkPayloadSource_1_1ScopedReaderSuspend.html", null ],
    [ "GaussianSplatRenderer::ScopedShadowPassState", "classGaussianSplatRenderer_1_1ScopedShadowPassState.html", null ],
    [ "GaussianSplatManager::ScopedSubmissionLock", "classGaussianSplatManager_1_1ScopedSubmissionLock.html", null ],
    [ "SelectionState", "structSelectionState.html", null ],
    [ "GaussianSplatting::PainterlyManager::Settings", "structGaussianSplatting_1_1PainterlyManager_1_1Settings.html", null ],
    [ "ShaderCompilationHelper", "classShaderCompilationHelper.html", null ],
    [ "ShaderCompilationManager", "classShaderCompilationManager.html", null ],
    [ "TileShaderCompilation::ShaderVariant", "structTileShaderCompilation_1_1ShaderVariant.html", null ],
    [ "GaussianRenderFacadeState::ShadowBlitState", "structGaussianRenderFacadeState_1_1ShadowBlitState.html", null ],
    [ "GaussianSplatRenderer::ShadowPassDescriptor", "structGaussianSplatRenderer_1_1ShadowPassDescriptor.html", null ],
    [ "GaussianSplatRenderer::ShadowRenderResult", "structGaussianSplatRenderer_1_1ShadowRenderResult.html", null ],
    [ "GaussianSplatManager::SharedDynamicAssetHandle", "structGaussianSplatManager_1_1SharedDynamicAssetHandle.html", null ],
    [ "SHCompressionMetrics", "structSHCompressionMetrics.html", null ],
    [ "SHConfig", "structSHConfig.html", null ],
    [ "StreamingUploadPipeline::PackTelemetry::Snapshot", "structStreamingUploadPipeline_1_1PackTelemetry_1_1Snapshot.html", null ],
    [ "GaussianSplatting::SortBenchmarkTimingMetrics", "structGaussianSplatting_1_1SortBenchmarkTimingMetrics.html", null ],
    [ "SortBufferHandles", "structSortBufferHandles.html", null ],
    [ "SorterCapabilities", "structSorterCapabilities.html", null ],
    [ "SortExternalBufferState", "structSortExternalBufferState.html", null ],
    [ "GaussianSplatting::SortFallbackPolicyDecision", "structGaussianSplatting_1_1SortFallbackPolicyDecision.html", null ],
    [ "SortFrameContext", "structSortFrameContext.html", null ],
    [ "GaussianRenderPerformance::SortFrameMetrics", "structGaussianRenderPerformance_1_1SortFrameMetrics.html", null ],
    [ "SortingMetrics", "structSortingMetrics.html", null ],
    [ "SortingMetricsCollector", "classSortingMetricsCollector.html", null ],
    [ "GaussianRenderState::SortingState", "structGaussianRenderState_1_1SortingState.html", null ],
    [ "SortingStrategyConfig", "structSortingStrategyConfig.html", null ],
    [ "GPUBufferManager::SortKey", "structGPUBufferManager_1_1SortKey.html", null ],
    [ "GaussianSplatting::SortKey64", "structGaussianSplatting_1_1SortKey64.html", null ],
    [ "SortKeyConfig", "structSortKeyConfig.html", null ],
    [ "SortOperationParams", "structSortOperationParams.html", null ],
    [ "SortOperationResult", "structSortOperationResult.html", null ],
    [ "GaussianSplatting::SortPaddingInfo", "structGaussianSplatting_1_1SortPaddingInfo.html", null ],
    [ "SortPositionInputs", "structSortPositionInputs.html", null ],
    [ "SortPreflightResult", "structSortPreflightResult.html", null ],
    [ "SortPublicationPayload", "structSortPublicationPayload.html", null ],
    [ "SortRuntimeState", "structSortRuntimeState.html", null ],
    [ "RenderPipelineStages::SortStage", "structRenderPipelineStages_1_1SortStage.html", null ],
    [ "GaussianSplatRenderer::SortStageInput", "structGaussianSplatRenderer_1_1SortStageInput.html", null ],
    [ "GaussianRenderPipeline::SortStageOutput", "structGaussianRenderPipeline_1_1SortStageOutput.html", null ],
    [ "GaussianRenderState::SortStageSummary", "structGaussianRenderState_1_1SortStageSummary.html", null ],
    [ "SortViewContext", "structSortViewContext.html", null ],
    [ "SphereEffectorGPU", "structSphereEffectorGPU.html", null ],
    [ "GaussianSplatting::SphereEffectorRenderData", "structGaussianSplatting_1_1SphereEffectorRenderData.html", null ],
    [ "GaussianSplatSceneDirector::SphereEffectorSelection", "structGaussianSplatSceneDirector_1_1SphereEffectorSelection.html", null ],
    [ "SPIRVDiskCache", "classSPIRVDiskCache.html", null ],
    [ "GaussianRenderDebug::SplatAuditSummary", "structGaussianRenderDebug_1_1SplatAuditSummary.html", null ],
    [ "GaussianSplatting::SplatChange", "structGaussianSplatting_1_1SplatChange.html", null ],
    [ "GaussianRenderPipeline::SplatDataSource", "structGaussianRenderPipeline_1_1SplatDataSource.html", null ],
    [ "GaussianSplatting::HierarchicalSplatStructure::SplatInfo", "structGaussianSplatting_1_1HierarchicalSplatStructure_1_1SplatInfo.html", null ],
    [ "SplatRefGPU", "structSplatRefGPU.html", null ],
    [ "SPZLoader::SPZHeader", "structSPZLoader_1_1SPZHeader.html", null ],
    [ "GaussianRenderPipeline::StageIO", "structGaussianRenderPipeline_1_1StageIO.html", null ],
    [ "GaussianRenderPipeline::StageMetrics", "structGaussianRenderPipeline_1_1StageMetrics.html", null ],
    [ "GaussianRenderPipeline::StageResult", "structGaussianRenderPipeline_1_1StageResult.html", null ],
    [ "GaussianSplatting::ComputeInfrastructure::StageResult", "structGaussianSplatting_1_1ComputeInfrastructure_1_1StageResult.html", null ],
    [ "GaussianSplatting::ComputeInfrastructure::StageValidationHarness", "classGaussianSplatting_1_1ComputeInfrastructure_1_1StageValidationHarness.html", null ],
    [ "GaussianSplatting::ComputeInfrastructure::StageValidationInput", "structGaussianSplatting_1_1ComputeInfrastructure_1_1StageValidationInput.html", null ],
    [ "GaussianSplatting::ComputeInfrastructure::StageValidationRecord", "structGaussianSplatting_1_1ComputeInfrastructure_1_1StageValidationRecord.html", null ],
    [ "GaussianRenderConfig::StateUniformData", "structGaussianRenderConfig_1_1StateUniformData.html", null ],
    [ "StaticChunk", "structStaticChunk.html", null ],
    [ "GaussianSplatting::HierarchicalSplatStructure::OctreeNode::Stats", "structGaussianSplatting_1_1HierarchicalSplatStructure_1_1OctreeNode_1_1Stats.html", null ],
    [ "GaussianMemoryStream::StreamBuffer", "structGaussianMemoryStream_1_1StreamBuffer.html", null ],
    [ "GaussianStreamingTypes::StreamingChunk", "structGaussianStreamingTypes_1_1StreamingChunk.html", null ],
    [ "StreamingChunkBakeRecord", "structStreamingChunkBakeRecord.html", null ],
    [ "StreamingEvictionController", "classStreamingEvictionController.html", null ],
    [ "StreamingGlobalAtlasRegistry", "classStreamingGlobalAtlasRegistry.html", null ],
    [ "StreamingQueuePressureController", "classStreamingQueuePressureController.html", null ],
    [ "GaussianRenderState::StreamingState", "structGaussianRenderState_1_1StreamingState.html", null ],
    [ "StreamingStats", "structStreamingStats.html", null ],
    [ "StreamingTelemetryAdapter", "classStreamingTelemetryAdapter.html", null ],
    [ "gs_tier_cap::StreamingTierCapPolicy", "structgs__tier__cap_1_1StreamingTierCapPolicy.html", null ],
    [ "StreamingUploadPipeline", "classStreamingUploadPipeline.html", null ],
    [ "StreamingVisibilityController", "classStreamingVisibilityController.html", null ],
    [ "GaussianSplatSceneDirector::SubmissionCounts", "structGaussianSplatSceneDirector_1_1SubmissionCounts.html", null ],
    [ "ResidentAtlasBudget::SubsetPlan", "structResidentAtlasBudget_1_1SubsetPlan.html", null ],
    [ "GaussianRenderFacadeState::SubsystemState", "structGaussianRenderFacadeState_1_1SubsystemState.html", null ],
    [ "GPUPerformanceMonitor::SummaryMetrics", "structGPUPerformanceMonitor_1_1SummaryMetrics.html", null ],
    [ "StreamingGlobalAtlasRegistry::SyncDiagnostics", "structStreamingGlobalAtlasRegistry_1_1SyncDiagnostics.html", null ],
    [ "GaussianRenderFacadeState::TestDataState", "structGaussianRenderFacadeState_1_1TestDataState.html", null ],
    [ "PainterlyPassGraph::TextureInfo", "structPainterlyPassGraph_1_1TextureInfo.html", null ],
    [ "GaussianRenderFrame::TextureTraceEntry", "structGaussianRenderFrame_1_1TextureTraceEntry.html", null ],
    [ "RenderDeviceManager::TextureTraceEntry", "structRenderDeviceManager_1_1TextureTraceEntry.html", null ],
    [ "GaussianSplatting::ThreadOwnedMutex", "classGaussianSplatting_1_1ThreadOwnedMutex.html", null ],
    [ "GaussianSplatting::ThreadOwnedMutexLock", "classGaussianSplatting_1_1ThreadOwnedMutexLock.html", null ],
    [ "TileAdaptiveController", "structTileAdaptiveController.html", null ],
    [ "GaussianSplatting::TileAdaptiveSettings", "structGaussianSplatting_1_1TileAdaptiveSettings.html", null ],
    [ "TileAsyncReadback", "structTileAsyncReadback.html", null ],
    [ "TileBinningStage", "structTileBinningStage.html", null ],
    [ "GaussianSplatting::TileBufferResizePlan", "structGaussianSplatting_1_1TileBufferResizePlan.html", null ],
    [ "GaussianSplatting::TileBufferShrinkPolicy", "structGaussianSplatting_1_1TileBufferShrinkPolicy.html", null ],
    [ "GaussianSplatting::TileConfigState", "structGaussianSplatting_1_1TileConfigState.html", null ],
    [ "GaussianSplatting::TileDebugCounterSnapshot", "structGaussianSplatting_1_1TileDebugCounterSnapshot.html", null ],
    [ "GaussianSplatting::TileDensityMetrics", "structGaussianSplatting_1_1TileDensityMetrics.html", null ],
    [ "GaussianSplatting::TileDeviceContext", "structGaussianSplatting_1_1TileDeviceContext.html", null ],
    [ "GaussianSplatting::TileDiagnosticsState", "structGaussianSplatting_1_1TileDiagnosticsState.html", null ],
    [ "GaussianSplatting::TileFrameState", "structGaussianSplatting_1_1TileFrameState.html", null ],
    [ "GaussianSplatting::TileGlobalSortResources", "structGaussianSplatting_1_1TileGlobalSortResources.html", null ],
    [ "GaussianSplatting::TileGridState", "structGaussianSplatting_1_1TileGridState.html", null ],
    [ "GaussianSplatting::TileLightingClusterABIConfig", "structGaussianSplatting_1_1TileLightingClusterABIConfig.html", null ],
    [ "GaussianSplatting::TileLightingSetABI", "structGaussianSplatting_1_1TileLightingSetABI.html", null ],
    [ "GaussianSplatting::TileOverflowStatsSnapshot", "structGaussianSplatting_1_1TileOverflowStatsSnapshot.html", null ],
    [ "GaussianSplatting::TilePerformanceMetrics", "structGaussianSplatting_1_1TilePerformanceMetrics.html", null ],
    [ "GaussianSplatting::TilePrefixCpuScanResult", "structGaussianSplatting_1_1TilePrefixCpuScanResult.html", null ],
    [ "GaussianSplatting::TilePrefixDispatchCounts", "structGaussianSplatting_1_1TilePrefixDispatchCounts.html", null ],
    [ "GaussianSplatting::TilePrefixParamsLayout", "structGaussianSplatting_1_1TilePrefixParamsLayout.html", null ],
    [ "GaussianSplatting::TilePrefixPass2ControlLayout", "structGaussianSplatting_1_1TilePrefixPass2ControlLayout.html", null ],
    [ "TilePrefixScanStage", "structTilePrefixScanStage.html", null ],
    [ "GaussianSplatting::TileProjectionBuffers", "structGaussianSplatting_1_1TileProjectionBuffers.html", null ],
    [ "TileProjectionLayout", "structTileProjectionLayout.html", null ],
    [ "TileRasterizerStage", "structTileRasterizerStage.html", null ],
    [ "TileRendererDebugStats", "structTileRendererDebugStats.html", null ],
    [ "GaussianRenderFacadeState::TileRendererState", "structGaussianRenderFacadeState_1_1TileRendererState.html", null ],
    [ "GaussianSplatting::TileRenderParams", "structGaussianSplatting_1_1TileRenderParams.html", null ],
    [ "TileRenderParamsBuilder", "structTileRenderParamsBuilder.html", null ],
    [ "TileRenderParamsGPU", "structTileRenderParamsGPU.html", null ],
    [ "GaussianSplatting::TileRenderSettings", "structGaussianSplatting_1_1TileRenderSettings.html", null ],
    [ "GaussianSplatting::TileRenderStats", "structGaussianSplatting_1_1TileRenderStats.html", null ],
    [ "GaussianSplatting::TileRenderTargets", "structGaussianSplatting_1_1TileRenderTargets.html", null ],
    [ "TileResolveStage", "structTileResolveStage.html", null ],
    [ "GaussianSplatting::TileResourceController", "structGaussianSplatting_1_1TileResourceController.html", null ],
    [ "GaussianSplatting::TileSceneLightingInputs", "structGaussianSplatting_1_1TileSceneLightingInputs.html", null ],
    [ "GaussianSplatting::TileShaderResources", "structGaussianSplatting_1_1TileShaderResources.html", null ],
    [ "GaussianSplatting::TileSHCacheBuffers", "structGaussianSplatting_1_1TileSHCacheBuffers.html", null ],
    [ "GaussianSplatting::TileSplatAuditSnapshot", "structGaussianSplatting_1_1TileSplatAuditSnapshot.html", null ],
    [ "GaussianSplatting::TileSubpixelHistoryBuffers", "structGaussianSplatting_1_1TileSubpixelHistoryBuffers.html", null ],
    [ "GaussianSplatting::TileSubpixelVisibilityBuffers", "structGaussianSplatting_1_1TileSubpixelVisibilityBuffers.html", null ],
    [ "GaussianSplatting::TileTimestampRange", "structGaussianSplatting_1_1TileTimestampRange.html", null ],
    [ "GaussianSplatting::TileTimingState", "structGaussianSplatting_1_1TileTimingState.html", null ],
    [ "GaussianSplatting::TileUniformBuffers", "structGaussianSplatting_1_1TileUniformBuffers.html", null ],
    [ "GaussianSplatting::HierarchicalSplatStructure::TreeStats", "structGaussianSplatting_1_1HierarchicalSplatStructure_1_1TreeStats.html", null ],
    [ "GaussianSplatting::ComputeInfrastructure::UniformBindingContract", "structGaussianSplatting_1_1ComputeInfrastructure_1_1UniformBindingContract.html", null ],
    [ "StreamingUploadPipeline::UploadBudgetState", "structStreamingUploadPipeline_1_1UploadBudgetState.html", null ],
    [ "StreamingUploadPipeline::UploadCoalescingCandidate", "structStreamingUploadPipeline_1_1UploadCoalescingCandidate.html", null ],
    [ "StreamingUploadPipeline::UploadCoalescingPlan", "structStreamingUploadPipeline_1_1UploadCoalescingPlan.html", null ],
    [ "RenderFrameContextManager::ViewState", "structRenderFrameContextManager_1_1ViewState.html", null ],
    [ "VisibleChunkRefGPU", "structVisibleChunkRefGPU.html", null ],
    [ "RenderStreamingOrchestrator::VisibleLODSelection", "structRenderStreamingOrchestrator_1_1VisibleLODSelection.html", null ],
    [ "StreamingQueuePressureController::VisibleScanStarvationInput", "structStreamingQueuePressureController_1_1VisibleScanStarvationInput.html", null ],
    [ "VRAMBudgetConfig", "structVRAMBudgetConfig.html", null ],
    [ "VRAMDebugStats", "structVRAMDebugStats.html", null ],
    [ "GaussianSplatPerformanceOverlay::FrameClock::Window", "structGaussianSplatPerformanceOverlay_1_1FrameClock_1_1Window.html", null ],
    [ "GaussianSplatSceneDirector::WorldSubmission", "structGaussianSplatSceneDirector_1_1WorldSubmission.html", null ],
    [ "GaussianSplatRenderer::WorldSubmissionContract", "structGaussianSplatRenderer_1_1WorldSubmissionContract.html", null ],
    [ "GaussianSplatSceneDirector::SubmissionStore::WorldSubmissionRecord", "structGaussianSplatSceneDirector_1_1SubmissionStore_1_1WorldSubmissionRecord.html", null ],
    [ "GaussianSplatRenderer::WorldSubmissionRuntimeStateSnapshot", "structGaussianSplatRenderer_1_1WorldSubmissionRuntimeStateSnapshot.html", null ],
    [ "StreamingVisibilityController::ZeroVisibleRecoveryState", "structStreamingVisibilityController_1_1ZeroVisibleRecoveryState.html", null ]
];