#!/usr/bin/env python3
"""Tests for the project-settings reference completeness guard and for the
generator's fail-on-disagreement contract.

Run: python tests/ci/test_check_project_settings_reference.py
"""
from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "tests" / "ci"))
sys.path.insert(0, str(REPO_ROOT / "scripts"))

import check_project_settings_reference as guard  # noqa: E402
import generate_project_settings_reference as generator  # noqa: E402

A = "rendering/gaussian_splatting/a/one"
B = "rendering/gaussian_splatting/b/two"
C = "rendering/gaussian_splatting/c/three"

PAGE = f"""# Project Settings Reference

> Hand notes mention `{C}` in prose; prose never counts.
> This block is hand-maintained. Everything below it is regenerated by `scripts/generate_project_settings_reference.py`.

<table>
  <tbody>
    <tr>
      <td><pre><code>{A}</code></pre></td>
      <td><pre><code>true</code></pre></td>
    </tr>
  </tbody>
</table>

| Setting | Note |
| --- | --- |
| `{B}` | read only |
"""


class GuardTest(unittest.TestCase):
    def test_matching_page_passes(self) -> None:
        self.assertEqual(guard.compare(guard.page_keys(PAGE), [A, B]), [])

    def test_key_deleted_from_page_fails(self) -> None:
        page = PAGE.replace(f"| `{B}` | read only |\n", "")
        failures = guard.compare(guard.page_keys(page), [A, B])
        self.assertEqual(failures, [f"{B}: in the manifest but missing from the page"])

    def test_manifest_key_added_without_regenerating_fails(self) -> None:
        failures = guard.compare(guard.page_keys(PAGE), [A, B, C])
        self.assertEqual(failures, [f"{C}: in the manifest but missing from the page"])

    def test_page_key_not_in_manifest_fails(self) -> None:
        failures = guard.compare(guard.page_keys(PAGE), [A])
        self.assertEqual(failures, [f"{B}: on the page but not in the manifest"])

    def test_duplicate_row_fails(self) -> None:
        page = PAGE + f"| `{B}` | again |\n"
        self.assertIn(f"{B}: listed 2 times on the page", guard.compare(guard.page_keys(page), [A, B]))

    def test_prose_mentions_do_not_count(self) -> None:
        self.assertNotIn(C, guard.page_keys(PAGE))

    def test_missing_marker_fails(self) -> None:
        page = PAGE.replace("> This block is hand-maintained.", "> This block is maintained by hand.")
        with self.assertRaisesRegex(ValueError, "generated region is unknown"):
            guard.page_keys(page)

    def test_empty_manifest_is_not_a_pass(self) -> None:
        self.assertTrue(guard.compare([], []))

    def test_repository_page_covers_repository_manifest(self) -> None:
        page = guard.page_keys(guard.PAGE_PATH.read_text(encoding="utf-8"))
        manifest = guard.manifest_keys(json.loads(guard.MANIFEST_PATH.read_text(encoding="utf-8")))
        self.assertGreater(len(manifest), 100)
        self.assertEqual(guard.compare(page, manifest), [])


def _source(rel: str, text: str) -> generator.SourceFile:
    source = generator.SourceFile(path=Path(rel), rel=rel, text=generator._strip_comments(text))
    generator._collect_definitions(source)
    return source


def _manifest(*keys: str, aliases: tuple[str, ...] = ()) -> dict:
    settings = [{"key": key} for key in keys]
    settings += [{"key": key, "publicness": "deprecated_alias"} for key in aliases]
    return {"families": [], "settings": settings}


class GeneratorScanTest(unittest.TestCase):
    def scan(self, *sources: generator.SourceFile) -> tuple[list, list]:
        return generator.collect_registrations(list(sources))

    def test_registration_forms_resolve(self) -> None:
        source = _source(
            "x.cpp",
            '#define SECTION "rendering/gaussian_splatting/m/"\n'
            "#define M_PATH SECTION \"macro\"\n"
            'const String Cfg::SECTION_PATH = "rendering/gaussian_splatting/c/";\n'
            'const String Cfg::K_PATH = SECTION_PATH + "constant";\n'
            'static const StringName local_path("rendering/gaussian_splatting/l/ctor");\n'
            "void f() {\n"
            "  // GLOBAL_DEF(\"rendering/gaussian_splatting/x/commented\", 1);\n"
            '  WARN_PRINT("GLOBAL_DEF(\\"rendering/gaussian_splatting/x/in_string\\", 1)");\n'
            "  GLOBAL_DEF(M_PATH, true);\n"
            "  GLOBAL_DEF(Cfg::K_PATH, 3);\n"
            "  GLOBAL_DEF_RST(\n"
            "      PropertyInfo(Variant::FLOAT,\n"
            '          "rendering/gaussian_splatting/p/multi_line",\n'
            '          PROPERTY_HINT_RANGE, "0,1,0.1"),\n'
            "      0.5f);\n"
            "  ps->set_initial_value(local_path, 1'000);\n"
            "}\n",
        )
        registrations, errors = self.scan(source)
        self.assertEqual(errors, [])
        found = {r.key: r.default for r in registrations}
        self.assertEqual(
            found,
            {
                "rendering/gaussian_splatting/m/macro": "true",
                "rendering/gaussian_splatting/c/constant": "3",
                "rendering/gaussian_splatting/p/multi_line": "0.5f",
                "rendering/gaussian_splatting/l/ctor": "1'000",
            },
        )

    def test_every_global_def_variant_registers(self) -> None:
        variants = (
            "GLOBAL_DEF_NOVAL",
            "GLOBAL_DEF_RST_NOVAL",
            "GLOBAL_DEF_NOVAL_BASIC",
            "GLOBAL_DEF_RST_NOVAL_BASIC",
            "GLOBAL_DEF_INTERNAL",
            "_GLOBAL_DEF",
        )
        body = "".join(f'  {macro}("rendering/gaussian_splatting/v/{macro.lower().strip("_")}", {i});\n' for i, macro in enumerate(variants))
        registrations, errors = self.scan(_source("x.cpp", "void f() {\n" + body + "}\n"))
        self.assertEqual(errors, [])
        self.assertEqual(
            {r.key: r.default for r in registrations},
            {f"rendering/gaussian_splatting/v/{macro.lower().strip('_')}": str(i) for i, macro in enumerate(variants)},
        )

    def test_helper_forwarding_a_default_uses_call_site_defaults(self) -> None:
        helper = _source(
            "h.h",
            "static inline const StringName &target_path() {\n"
            '  return make(&cache, "rendering/gaussian_splatting/d/target");\n'
            "}\n"
            "static inline void register_target(ProjectSettings *p_ps, float p_default_value) {\n"
            "  GLOBAL_DEF(String(target_path()), p_default_value);\n"
            "}\n",
        )
        caller = _source("c.cpp", "void g() { register_target(ps, 2.0f); }\n")
        registrations, errors = self.scan(helper, caller)
        self.assertEqual(errors, [])
        self.assertEqual([(r.key, r.default, r.file) for r in registrations], [("rendering/gaussian_splatting/d/target", "2.0f", "c.cpp")])

    def test_unresolvable_key_fails(self) -> None:
        _, errors = self.scan(_source("x.cpp", "void f() { GLOBAL_DEF(UNKNOWN_PATH, 1); }\n"))
        self.assertEqual(len(errors), 1)
        self.assertIn("cannot resolve", errors[0])

    def test_registered_key_missing_from_manifest_fails(self) -> None:
        registrations, _ = self.scan(_source("x.cpp", f'void f() {{ GLOBAL_DEF("{A}", 1); GLOBAL_DEF("{B}", 1); }}\n'))
        _, errors = generator.build_model(_manifest(A), registrations)
        self.assertEqual(len(errors), 1)
        self.assertIn(f"{B}: registered in source", errors[0])

    def test_conflicting_defaults_fail(self) -> None:
        registrations, _ = self.scan(
            _source("x.cpp", f'void f() {{ GLOBAL_DEF("{A}", 1); }}\n'),
            _source("y.cpp", f'void g() {{ GLOBAL_DEF("{A}", 2); }}\n'),
        )
        _, errors = generator.build_model(_manifest(A), registrations)
        self.assertEqual(len(errors), 1)
        self.assertIn("conflicting defaults", errors[0])

    def test_registered_alias_fails(self) -> None:
        registrations, _ = self.scan(_source("x.cpp", f'void f() {{ GLOBAL_DEF("{A}", 1); }}\n'))
        _, errors = generator.build_model(_manifest(aliases=(A,)), registrations)
        self.assertEqual(len(errors), 1)
        self.assertIn("deprecated alias", errors[0])

    def test_manifest_key_neither_registered_nor_read_fails(self) -> None:
        registrations, _ = self.scan(_source("x.cpp", f'void f() {{ GLOBAL_DEF("{A}", 1); }}\n'))
        manifest = _manifest(A, B, C)
        by_key, _ = generator.build_model(manifest, registrations)
        errors = generator.unreferenced_errors(manifest, by_key, referenced={A, B})
        self.assertEqual(errors, [f"{C}: in the manifest, but the source neither registers nor reads it"])

    def test_rendered_page_lists_every_manifest_key_once(self) -> None:
        registrations, _ = self.scan(_source("x.cpp", f'void f() {{ GLOBAL_DEF("{A}", 1); }}\n'))
        manifest = _manifest(A, B, aliases=(C,))
        by_key, errors = generator.build_model(manifest, registrations)
        self.assertEqual(errors, [])
        page = generator.build_reference(manifest, by_key, [generator.MANUAL_BLOCK_MARKER])
        self.assertEqual(guard.compare(guard.page_keys(page), [A, B, C]), [])


if __name__ == "__main__":
    unittest.main(verbosity=2)
