#!/usr/bin/env python3
"""Generate a ProjectSettings reference for the Gaussian Splatting module."""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
from collections import defaultdict

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "reference" / "project-settings.md"
SOURCE_ROOT = ROOT / "modules" / "gaussian_splatting"

PATTERN = re.compile(r'GLOBAL_DEF\(\"(?P<key>rendering/gaussian_splatting[^\"]*)\",\s*(?P<value>[^;]+)\);')
# Match only string literals that are EXACTLY a setting key: quote, key-shaped
# characters, quote. Using [^"]* here would capture whole log/WARN sentences that
# merely mention a key mid-string (e.g. "<key> is deprecated ..."), producing
# bogus "runtime-only" rows. Real keys are [A-Za-z0-9_/] only, so the closing
# quote must immediately follow the key.
KEY_LITERAL_PATTERN = re.compile(r'"(?P<key>rendering/gaussian_splatting[A-Za-z0-9_/]*)"')

# The reference file carries a hand-maintained blockquote region (manual
# annotations) between the header and the generated tables, terminated by this
# exact marker line. Regeneration MUST preserve that region verbatim; it is not
# reproducible from source. Everything after the marker is regenerated.
MANUAL_BLOCK_MARKER = (
    "> This block is hand-maintained. The rest of this file is regenerated by the script above."
)


def extract_manual_block(existing_text: str) -> list[str]:
    """Return the contiguous hand-maintained blockquote region (up to and
    including MANUAL_BLOCK_MARKER) from an existing reference file, or [] if the
    marker is absent (first generation)."""
    lines = existing_text.splitlines()
    marker_idx = next(
        (i for i, line in enumerate(lines) if line.strip() == MANUAL_BLOCK_MARKER),
        None,
    )
    if marker_idx is None:
        return []
    start = marker_idx
    while start - 1 >= 0 and lines[start - 1].startswith(">"):
        start -= 1
    return lines[start : marker_idx + 1]

GROUP_ORDER = [
    "core",
    "world",
    "import",
    "quality",
    "streaming",
    "culling",
    "cull",
    "lod",
    "sorting",
    "debug",
    "logging",
    "diagnostics",
    "other",
]

KNOWN_GROUPS = set(GROUP_ORDER)


@dataclass
class SettingEntry:
    key: str
    value: str
    path: Path
    line: int

    @property
    def group(self) -> str:
        parts = self.key.split("/")
        if len(parts) < 3:
            return "core"
        if len(parts) == 3:
            return "core"
        group = parts[2]
        return group if group in KNOWN_GROUPS else "other"


@dataclass
class KeyReference:
    key: str
    path: Path
    line: int


def collect_entries() -> list[SettingEntry]:
    entries: list[SettingEntry] = []
    # Sort the traversal so output is deterministic across filesystems/platforms.
    for path in sorted(SOURCE_ROOT.rglob("*.cpp")):
        rel = path.relative_to(ROOT)
        for idx, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            match = PATTERN.search(line)
            if not match:
                continue
            key = match.group("key").strip()
            value = match.group("value").strip().rstrip(";")
            entries.append(SettingEntry(key=key, value=value, path=rel, line=idx))
    entries.sort(key=lambda entry: entry.key)
    return entries


def collect_key_references() -> dict[str, list[KeyReference]]:
    references: dict[str, list[KeyReference]] = defaultdict(list)
    # Sort the traversal so the "first reference" chosen per key (references[key][0])
    # is deterministic across filesystems/platforms, not filesystem-order dependent.
    for path in sorted(SOURCE_ROOT.rglob("*")):
        if path.suffix not in {".cpp", ".h"}:
            continue
        rel = path.relative_to(ROOT)
        if "tests" in rel.parts:
            continue
        for idx, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            for match in KEY_LITERAL_PATTERN.finditer(line):
                key = match.group("key").strip()
                references[key].append(KeyReference(key=key, path=rel, line=idx))
    return references


def render_table(entries: list[SettingEntry]) -> list[str]:
    rows = [
        "<table>",
        "  <thead>",
        "    <tr>",
        "      <th>Setting</th>",
        "      <th>Default</th>",
        "      <th>Defined In</th>",
        "    </tr>",
        "  </thead>",
        "  <tbody>",
    ]
    for entry in entries:
        rows.extend(
            [
                "    <tr>",
                f"      <td><pre><code>{entry.key}</code></pre></td>",
                f"      <td><pre><code>{entry.value}</code></pre></td>",
                f"      <td><pre><code>{entry.path.as_posix()}:{entry.line}</code></pre></td>",
                "    </tr>",
            ]
        )
    rows.extend(["  </tbody>", "</table>"])
    return rows


def render_runtime_only_table(runtime_only: list[tuple[str, KeyReference]]) -> list[str]:
    rows = [
        "| Setting | First reference |",
        "| --- | --- |",
    ]
    for key, reference in runtime_only:
        rows.append(f"| `{key}` | `{reference.path.as_posix()}:{reference.line}` |")
    return rows


def render_unconsumed_table(unconsumed: list[SettingEntry]) -> list[str]:
    rows = [
        "| Setting | Registered in |",
        "| --- | --- |",
    ]
    for entry in unconsumed:
        rows.append(f"| `{entry.key}` | `{entry.path.as_posix()}:{entry.line}` |")
    return rows


def has_non_registration_reference(entry: SettingEntry, references: dict[str, list[KeyReference]]) -> bool:
    for reference in references.get(entry.key, []):
        if reference.path != entry.path or reference.line != entry.line:
            return True
    return False


def build_reference(manual_block: list[str] | None = None) -> str:
    entries = collect_entries()
    references = collect_key_references()
    grouped: dict[str, list[SettingEntry]] = {group: [] for group in GROUP_ORDER}
    for entry in entries:
        grouped.setdefault(entry.group, []).append(entry)

    registered_keys = {entry.key for entry in entries}
    runtime_only = [
        (key, references[key][0])
        for key in sorted(references.keys())
        if key not in registered_keys and not key.endswith("/")
    ]
    unconsumed = [entry for entry in entries if not has_non_registration_reference(entry, references)]

    # No "Last generated" timestamp: it would make the output non-reproducible
    # (a regen on a different day would churn the file). Git history records when
    # the reference was regenerated.
    sections: list[str] = [
        "# Project Settings Reference",
        "",
    ]
    # Re-inject the hand-maintained annotation region verbatim (see extract_manual_block).
    if manual_block:
        sections.extend(manual_block)
        sections.append("")
    sections.extend([
        "## Purpose",
        "Use this reference to map Gaussian Splatting project setting keys to source definitions and runtime lookup paths.",
        "",
        "## Usage",
        "| Task | Action |",
        "| --- | --- |",
        "| Regenerate this reference | Run `python3 scripts/generate_project_settings_reference.py`. |",
        "| Audit key usage in module code | Run `rg -n \"rendering/gaussian_splatting/\" modules/gaussian_splatting --glob '*.{h,cpp}'`. |",
        "",
        "## API",
        "",
        "### Registered keys",
        "These settings are registered with `GLOBAL_DEF(...)` and grouped by key prefix.",
        "",
        "| Coverage | Count |",
        "| --- | ---: |",
        f"| Registered keys | {len(entries)} |",
        f"| Runtime-only keys | {len(runtime_only)} |",
        f"| Registered keys without additional literal lookup | {len(unconsumed)} |",
        "",
    ])

    for group in GROUP_ORDER:
        group_entries = grouped.get(group, [])
        if not group_entries:
            continue
        title = group.replace("_", " ").title()
        sections.extend([f"#### {title}", ""])
        sections.extend(render_table(group_entries))
        sections.append("")

    sections.extend(
        [
            "### Runtime-only keys",
            "These keys are used by module code but are not registered with `GLOBAL_DEF(...)`.",
            "",
        ]
    )
    if runtime_only:
        sections.extend(render_runtime_only_table(runtime_only))
    else:
        sections.append("No runtime-only keys found.")
    sections.append("")

    sections.extend(
        [
            "### Registered keys without additional literal lookup",
            "These registered keys have no additional string-literal references beyond their registration line.",
            "",
        ]
    )
    if unconsumed:
        sections.extend(render_unconsumed_table(unconsumed))
    else:
        sections.append("No registered keys without additional literal lookup found.")
    sections.append("")

    sections.extend(
        [
            "## Examples",
            "```bash",
            "python3 scripts/generate_project_settings_reference.py",
            "```",
            "",
            "```bash",
            "rg -n \"rendering/gaussian_splatting/\" modules/gaussian_splatting --glob '*.{h,cpp}'",
            "```",
            "",
            "## Troubleshooting",
            "| Issue | Cause | Fix |",
            "| --- | --- | --- |",
            "| A key exists in code but not under registered sections | The key is read at runtime without `GLOBAL_DEF(...)`. | Check the `Runtime-only keys` section and decide whether to register it. |",
            "| A registered key appears unconsumed | No extra string-literal lookup path is present in module runtime code. | Verify lookup paths or remove stale registration. |",
            "| Line references are stale | Source moved after docs were generated. | Regenerate this file after code changes. |",
        ]
    )

    return "\n".join(sections)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    # Preserve the existing hand-maintained annotation region across regeneration.
    manual_block = (
        extract_manual_block(OUTPUT.read_text(encoding="utf-8")) if OUTPUT.exists() else []
    )
    # Force LF and forward-slash paths so output is identical on Windows and Linux.
    # Use open(..., newline="\n") rather than Path.write_text(newline=...), which is
    # only available on Python 3.10+ (this repo still supports 3.8).
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(build_reference(manual_block) + "\n")
    print(f"[docs] Wrote project settings reference to {OUTPUT}")


if __name__ == "__main__":
    main()
