#!/usr/bin/env python3
"""Generate the ProjectSettings reference for the Gaussian Splatting module.

Key set: `modules/gaussian_splatting/config/project_settings_manifest.json` is the
authority. Every manifest key appears on the page exactly once.

Registration facts (default value, registering file): a scan of the module's
production C++ for every registration form the code uses --
`GLOBAL_DEF*(key, default)` (key as a literal, a constant, a macro, a
`PropertyInfo(...)` second argument or a path-returning function, any number
of lines), `ProjectSettings::set_initial_value(key, default)`, and
helper functions that forward a `p_*` default parameter to `GLOBAL_DEF`.

Generation FAILS (exit 1, nothing written) instead of guessing when the two
sources disagree:
- a registration whose key expression cannot be resolved to a setting path;
- a registered key missing from the manifest;
- a manifest deprecated alias that the source registers;
- one key registered with two different default expressions;
- a manifest key (other than an alias) that the source neither registers nor
  reads, as judged by the manifest guard's own source scan.

Manifest keys that the source reads but never registers are listed in their
own table, so the page still covers every manifest key.
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "reference" / "project-settings.md"
MODULE_ROOT = ROOT / "modules" / "gaussian_splatting"
MANIFEST_PATH = MODULE_ROOT / "config" / "project_settings_manifest.json"
SETTING_PREFIX = "rendering/gaussian_splatting/"
SOURCE_SUFFIXES = {".cpp", ".h"}
# Same production-source definition as modules/gaussian_splatting/tests/check_project_settings_manifest.py.
SOURCE_EXCLUDE_PARTS = {"tests", "doc_classes"}
ALIAS_PUBLICNESS = {"deprecated_alias"}
ALIAS_SCOPES = {"migration_alias"}

# The reference file carries a hand-maintained blockquote region (manual
# annotations) between the header and the generated tables, terminated by this
# exact marker line. Regeneration MUST preserve that region verbatim; it is not
# reproducible from source. Everything after the marker is regenerated.
MANUAL_BLOCK_MARKER = (
    "> This block is hand-maintained. Everything below it is regenerated by"
    " `scripts/generate_project_settings_reference.py`."
)
# Earlier marker wording, still recognised so a regeneration over an older copy
# of the file keeps its hand-maintained block instead of silently dropping it.
LEGACY_MANUAL_BLOCK_MARKERS = (
    "> This block is hand-maintained. The rest of this file is regenerated by the script above.",
)


class GenerationError(Exception):
    """Manifest and source disagree, or the source cannot be resolved."""


def extract_manual_block(existing_text: str) -> list[str]:
    """Return the contiguous hand-maintained blockquote region (up to and
    including MANUAL_BLOCK_MARKER) from an existing reference file, or [] if the
    marker is absent (first generation)."""
    lines = existing_text.splitlines()
    markers = (MANUAL_BLOCK_MARKER, *LEGACY_MANUAL_BLOCK_MARKERS)
    marker_idx = next(
        (i for i, line in enumerate(lines) if line.strip() in markers),
        None,
    )
    if marker_idx is None:
        return []
    start = marker_idx
    while start - 1 >= 0 and lines[start - 1].startswith(">"):
        start -= 1
    # Always re-emit the current marker wording.
    return [*lines[start:marker_idx], MANUAL_BLOCK_MARKER]


# --------------------------------------------------------------------------
# C++ source scanning
# --------------------------------------------------------------------------

STRING_RE = re.compile(r'"((?:[^"\\\n]|\\.)*)"')
IDENT_RE = r"[A-Za-z_][A-Za-z0-9_]*"
QUALIFIED_RE = rf"(?:{IDENT_RE}::)*{IDENT_RE}"
DEFINE_RE = re.compile(rf"^[ \t]*#[ \t]*define[ \t]+({IDENT_RE})[ \t]+(.+)$", re.M)
STRING_TYPE = r"(?:String|StringName|char\s*\*|char)"
ASSIGN_RE = re.compile(
    rf"(?:\bstatic\s+|\binline\s+|\bconstexpr\s+|\bconst\s+)*{STRING_TYPE}\s*(?:const\s+)?"
    rf"({QUALIFIED_RE})\s*(?:\[\s*\])?\s*=\s*([^;{{}}]+);"
)
CTOR_RE = re.compile(
    rf"(?:\bstatic\s+|\bconst\s+)*(?:String|StringName)\s+({QUALIFIED_RE})\s*\(\s*(\"(?:[^\"\\\n]|\\.)*\")\s*\)\s*;"
)
FUNC_RETURN_RE = re.compile(rf"({QUALIFIED_RE})\s*\(\s*\)\s*(?:const\s*)?\{{\s*return\b([^;]*);", re.S)
# Every macro of the GLOBAL_DEF family (core/config/project_settings.h: _RST,
# _NOVAL, _BASIC, _INTERNAL and their combinations, plus _GLOBAL_DEF itself)
# takes (key, default) first, so the whole family is matched by prefix rather
# than enumerated: a variant missing from a list would otherwise be reported
# as "read but not registered" without its default.
REGISTRATION_CALL_RE = re.compile(r"(?<![A-Za-z0-9])(_?GLOBAL_DEF[A-Z0-9_]*)\s*\(|(?:->|\.)\s*(set_initial_value)\s*\(")
FUNC_HEADER_RE = re.compile(rf"\b({QUALIFIED_RE})\s*\(([^()]*)\)\s*(?:const\s*)?\{{")
EXPR_TOKEN_RE = re.compile(rf'"((?:[^"\\]|\\.)*)"|({QUALIFIED_RE})(\s*\(\s*\))?')
WRAPPER_TOKENS = {"String", "StringName", "SNAME", "_SNAME"}


def _strip_comments(text: str) -> str:
    """Blank out // and /* */ comments (keeping newlines and string literals)."""
    out: list[str] = []
    i, n = 0, len(text)
    while i < n:
        c = text[i]
        if c == '"' or (c == "'" and not (i > 0 and text[i - 1].isalnum())):  # not a 1'000 digit separator
            j = i + 1
            while j < n and text[j] != c:
                j += 2 if text[j] == "\\" else 1
            out.append(text[i : j + 1])
            i = j + 1
        elif text.startswith("//", i):
            j = text.find("\n", i)
            j = n if j == -1 else j
            out.append(" " * (j - i))
            i = j
        elif text.startswith("/*", i):
            j = text.find("*/", i + 2)
            j = n if j == -1 else j + 2
            out.append("".join(ch if ch == "\n" else " " for ch in text[i:j]))
            i = j
        else:
            out.append(c)
            i += 1
    return "".join(out)


def _string_spans(text: str) -> list[tuple[int, int]]:
    return [m.span() for m in STRING_RE.finditer(text)]


def _inside(spans: list[tuple[int, int]], pos: int) -> bool:
    return any(start <= pos < end for start, end in spans)


def _balanced_args(text: str, open_paren: int) -> tuple[list[str], int]:
    """Split the argument list starting at text[open_paren] == '(' at top-level
    commas. Returns (args, index after the closing paren)."""
    depth = 0
    args: list[str] = []
    current: list[str] = []
    i = open_paren
    while i < len(text):
        c = text[i]
        if c == '"' or (c == "'" and not (i > 0 and text[i - 1].isalnum())):  # not a 1'000 digit separator
            j = i + 1
            while j < len(text) and text[j] != c:
                j += 2 if text[j] == "\\" else 1
            current.append(text[i : j + 1])
            i = j + 1
            continue
        if c in "([{":
            depth += 1
            if depth > 1:
                current.append(c)
        elif c in ")]}":
            depth -= 1
            if depth == 0:
                args.append("".join(current).strip())
                return args, i + 1
            current.append(c)
        elif c == "," and depth == 1:
            args.append("".join(current).strip())
            current = []
        else:
            current.append(c)
        i += 1
    raise GenerationError("unbalanced parentheses")


def _normalize(expr: str) -> str:
    return re.sub(r"\s+", " ", expr).strip()


def _decode(literal: str) -> str:
    return bytes(literal, "utf-8").decode("unicode_escape")


def _is_setting_path(value: str) -> bool:
    return value.startswith(SETTING_PREFIX) and re.fullmatch(r"[A-Za-z0-9_/]+", value) is not None and not value.endswith("/")


@dataclass
class SourceFile:
    path: Path
    rel: str
    text: str  # comments blanked
    defs: dict[str, str] = field(default_factory=dict)


@dataclass
class Registration:
    key: str
    default: str
    file: str
    line: int
    mechanism: str


class Resolver:
    """Resolve C++ string-constant expressions to setting paths.

    Lookup for a name: the file's own definitions, then the definition
    qualified by the current class context, then a unique global value.
    Two different global values for one name is an error, never a guess."""

    def __init__(self, files: list[SourceFile]):
        self.files = files
        self.global_defs: dict[str, set[str]] = defaultdict(set)
        for source in files:
            for name, expr in source.defs.items():
                self.global_defs[name].add(expr)
        # Unqualified view of qualified definitions, e.g. SECTION_PATH -> {GPUSortingConfig::SECTION_PATH}.
        self.by_tail: dict[str, set[str]] = defaultdict(set)
        for name in self.global_defs:
            self.by_tail[name.split("::")[-1]].add(name)

    def _candidates(self, name: str, source: SourceFile, context: str) -> list[tuple[str, str]]:
        if name in source.defs:
            return [(name, source.defs[name])]
        if context and f"{context}::{name}" in self.global_defs:
            qualified = f"{context}::{name}"
            return [(qualified, expr) for expr in self.global_defs[qualified]]
        if name in self.global_defs:
            return [(name, expr) for expr in self.global_defs[name]]
        if "::" not in name:
            qualified_names = self.by_tail.get(name, set())
            return [(q, expr) for q in sorted(qualified_names) for expr in self.global_defs[q]]
        return []

    def resolve(self, expr: str, source: SourceFile, context: str = "", depth: int = 0) -> str | None:
        if depth > 25:
            return None
        value = ""
        had_token = False
        for match in EXPR_TOKEN_RE.finditer(expr):
            literal, name, call = match.groups()
            if literal is not None:
                value += _decode(literal)
                had_token = True
                continue
            if name in WRAPPER_TOKENS and not call:
                continue
            lookup = f"{name}()" if call else name
            results: set[str] = set()
            for qualified, definition in self._candidates(lookup, source, context):
                next_context = qualified.rsplit("::", 1)[0] if "::" in qualified.rstrip("()") else context
                owner = self._owner_file(qualified, definition) or source
                resolved = self.resolve(definition, owner, next_context, depth + 1)
                if resolved is not None:
                    results.add(resolved)
            if len(results) != 1:
                return None
            value += results.pop()
            had_token = True
        return value if had_token else None

    def _owner_file(self, name: str, expr: str) -> SourceFile | None:
        for source in self.files:
            if source.defs.get(name) == expr:
                return source
        return None


def _collect_definitions(source: SourceFile) -> None:
    text = source.text
    for match in DEFINE_RE.finditer(text):
        source.defs.setdefault(match.group(1), match.group(2).strip())
    for match in ASSIGN_RE.finditer(text):
        source.defs.setdefault(match.group(1), match.group(2).strip())
    for match in CTOR_RE.finditer(text):
        source.defs.setdefault(match.group(1), match.group(2).strip())
    for match in FUNC_RETURN_RE.finditer(text):
        paths = [_decode(m.group(1)) for m in STRING_RE.finditer(match.group(2))]
        paths = [p for p in paths if _is_setting_path(p)]
        if len(paths) == 1:
            name = match.group(1)
            source.defs.setdefault(f"{name}()", f'"{paths[0]}"')
            source.defs.setdefault(f"{name.split('::')[-1]}()", f'"{paths[0]}"')


def load_sources() -> list[SourceFile]:
    files: list[SourceFile] = []
    for path in sorted(MODULE_ROOT.rglob("*")):
        if path.suffix not in SOURCE_SUFFIXES or not path.is_file():
            continue
        if set(path.relative_to(MODULE_ROOT).parts) & SOURCE_EXCLUDE_PARTS:
            continue
        raw = path.read_text(encoding="utf-8", errors="replace")
        source = SourceFile(path=path, rel=path.relative_to(ROOT).as_posix(), text=_strip_comments(raw))
        _collect_definitions(source)
        files.append(source)
    return files


def _enclosing_function(text: str, pos: int) -> tuple[str, list[str]] | None:
    """Nearest function header that opens before `pos`: (name, parameter names)."""
    best = None
    for match in FUNC_HEADER_RE.finditer(text, 0, pos):
        best = match
    if best is None:
        return None
    params = []
    for raw in best.group(2).split(","):
        found = re.findall(IDENT_RE, raw)
        if found:
            params.append(found[-1])
    return best.group(1), params


def _calls_of(function: str, files: list[SourceFile]) -> list[tuple[SourceFile, int, list[str]]]:
    tail = function.split("::")[-1]
    calls = []
    pattern = re.compile(rf"(?<![A-Za-z0-9_])(?:{IDENT_RE}::)*{re.escape(tail)}\s*\(")
    for source in files:
        spans = _string_spans(source.text)
        for match in pattern.finditer(source.text):
            if _inside(spans, match.start()):
                continue
            args, end = _balanced_args(source.text, match.end() - 1)
            # Skip the definition itself (followed by a body).
            if re.match(r"\s*(?:const\s*)?\{", source.text[end:]):
                continue
            calls.append((source, source.text.count("\n", 0, match.start()) + 1, args))
    return calls


def collect_registrations(files: list[SourceFile]) -> tuple[list[Registration], list[str]]:
    resolver = Resolver(files)
    registrations: list[Registration] = []
    errors: list[str] = []
    for source in files:
        spans = _string_spans(source.text)
        for match in REGISTRATION_CALL_RE.finditer(source.text):
            if _inside(spans, match.start()):
                continue
            mechanism = match.group(1) or match.group(2)
            line = source.text.count("\n", 0, match.start()) + 1
            # `#define GLOBAL_DEF...` style definitions are not registrations.
            line_start = source.text.rfind("\n", 0, match.start()) + 1
            if source.text[line_start : match.start()].lstrip().startswith("#"):
                continue
            try:
                args, _ = _balanced_args(source.text, match.end() - 1)
            except GenerationError:
                errors.append(f"{source.rel}:{line}: unbalanced {mechanism}(...) call")
                continue
            if len(args) < 2:
                errors.append(f"{source.rel}:{line}: {mechanism}(...) without a default argument")
                continue
            key_expr, default_expr = args[0], args[1]
            if key_expr.startswith("PropertyInfo"):
                inner, _ = _balanced_args(key_expr, key_expr.index("("))
                if len(inner) < 2:
                    errors.append(f"{source.rel}:{line}: PropertyInfo(...) without a name argument")
                    continue
                key_expr = inner[1]
            key = resolver.resolve(key_expr, source)
            if key is None or not _is_setting_path(key):
                if key is not None and not key.startswith(SETTING_PREFIX):
                    continue  # a non-Gaussian setting (none today); not this page's concern
                errors.append(f"{source.rel}:{line}: cannot resolve {mechanism} key expression `{_normalize(key_expr)}`")
                continue
            default = _normalize(default_expr)
            if re.fullmatch(r"p_[A-Za-z0-9_]+", default):
                # A helper forwards its parameter: the defaults are at its call sites.
                enclosing = _enclosing_function(source.text, match.start())
                if enclosing is None or default not in enclosing[1]:
                    errors.append(f"{source.rel}:{line}: default `{default}` is not a parameter of the enclosing function")
                    continue
                helper, params = enclosing
                index = params.index(default)
                calls = _calls_of(helper, files)
                if not calls:
                    errors.append(f"{source.rel}:{line}: helper `{helper}` registers `{key}` but is never called")
                for call_source, call_line, call_args in calls:
                    if index >= len(call_args):
                        errors.append(f"{call_source.rel}:{call_line}: call of `{helper}` has no argument {index + 1}")
                        continue
                    registrations.append(
                        Registration(key, _normalize(call_args[index]), call_source.rel, call_line, f"{helper}() -> {mechanism}")
                    )
                continue
            registrations.append(Registration(key, default, source.rel, line, mechanism))
    return registrations, errors


# --------------------------------------------------------------------------
# Manifest
# --------------------------------------------------------------------------


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def manifest_entries(manifest: dict) -> dict[str, dict]:
    families = sorted(manifest.get("families", []), key=lambda family: len(family.get("prefix", "")))
    entries: dict[str, dict] = {}
    for entry in manifest.get("settings", []):
        key = entry["key"]
        if key in entries:
            raise GenerationError(f"manifest lists {key} twice")
        resolved: dict = {}
        for family in families:
            if key.startswith(family.get("prefix", "\0")):
                resolved.update({k: v for k, v in family.items() if k != "prefix"})
        resolved.update(entry)
        entries[key] = resolved
    return entries


def _is_alias(entry: dict) -> bool:
    return entry.get("publicness") in ALIAS_PUBLICNESS or entry.get("scope") in ALIAS_SCOPES


def build_model(manifest: dict, registrations: list[Registration]) -> tuple[dict[str, list[Registration]], list[str]]:
    entries = manifest_entries(manifest)
    by_key: dict[str, list[Registration]] = defaultdict(list)
    for registration in registrations:
        by_key[registration.key].append(registration)
    errors: list[str] = []
    for key in sorted(by_key):
        sites = ", ".join(f"{r.file}:{r.line}" for r in by_key[key])
        if key not in entries:
            errors.append(f"{key}: registered in source ({sites}) but missing from project_settings_manifest.json")
            continue
        if _is_alias(entries[key]):
            errors.append(f"{key}: manifest says deprecated alias, but the source registers it ({sites})")
        defaults = {r.default for r in by_key[key]}
        if len(defaults) > 1:
            errors.append(f"{key}: registered with conflicting defaults {sorted(defaults)} ({sites})")
    return by_key, errors


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------


def _group(key: str) -> str:
    rest = key[len(SETTING_PREFIX):]
    return rest.split("/", 1)[0] if "/" in rest else "(top level)"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _html(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def render_registered_table(keys: list[str], by_key: dict[str, list[Registration]]) -> list[str]:
    rows = [
        "<table>",
        "  <thead>",
        "    <tr>",
        "      <th>Setting</th>",
        "      <th>Default (as registered)</th>",
        "      <th>Registered in</th>",
        "    </tr>",
        "  </thead>",
        "  <tbody>",
    ]
    for key in keys:
        registrations = by_key[key]
        files = sorted({r.file for r in registrations})
        rows.extend(
            [
                "    <tr>",
                f"      <td><pre><code>{key}</code></pre></td>",
                f"      <td><pre><code>{_html(registrations[0].default)}</code></pre></td>",
                f"      <td><pre><code>{'<br>'.join(files)}</code></pre></td>",
                "    </tr>",
            ]
        )
    rows.extend(["  </tbody>", "</table>"])
    return rows


def build_reference(manifest: dict, by_key: dict[str, list[Registration]], manual_block: list[str] | None = None) -> str:
    entries = manifest_entries(manifest)
    aliases = sorted(key for key, entry in entries.items() if _is_alias(entry))
    registered = sorted(key for key in entries if key in by_key)
    unregistered = sorted(key for key in entries if key not in by_key and key not in aliases)

    grouped: dict[str, list[str]] = defaultdict(list)
    for key in registered:
        grouped[_group(key)].append(key)
    group_order = sorted(grouped, key=lambda group: (group != "(top level)", group))

    # No "Last generated" timestamp: the output must be a pure function of the
    # manifest and the source, so CI can freshness-check it.
    sections: list[str] = ["# Project Settings Reference", ""]
    if manual_block:
        sections.extend(manual_block)
        sections.append("")
    sections.extend(
        [
            "## Purpose",
            "Every Gaussian Splatting project setting key, its registered default, and the source file that registers it.",
            "",
            "The key set comes from `modules/gaussian_splatting/config/project_settings_manifest.json`. The defaults and",
            "registering files come from the module source. Generation fails when the two disagree.",
            "A default is shown as the C++ expression passed at registration (for example a named constant), not as an evaluated value.",
            "",
            "## Usage",
            "| Task | Action |",
            "| --- | --- |",
            "| Regenerate this reference | Run `python3 scripts/generate_project_settings_reference.py`. |",
            "| Check this page covers the manifest | Run `python3 tests/ci/check_project_settings_reference.py`. |",
            "",
            "## API",
            "",
            "### Coverage",
            "",
            "| Coverage | Count |",
            "| --- | ---: |",
            f"| Keys in the manifest | {len(entries)} |",
            f"| Registered by the module at startup | {len(registered)} |",
            f"| Read by the module but not registered | {len(unregistered)} |",
            f"| Deprecated aliases (read only, never registered) | {len(aliases)} |",
            "",
            "### Registered keys",
            "Registered through `GLOBAL_DEF(...)`, `GLOBAL_DEF_RST(...)` or `ProjectSettings::set_initial_value(...)`, grouped by key prefix.",
            "",
        ]
    )
    for group in group_order:
        sections.extend([f"#### {group}", ""])
        sections.extend(render_registered_table(grouped[group], by_key))
        sections.append("")

    sections.extend(
        [
            "### Read but not registered",
            "Listed in the manifest and read by module code, but not registered: they do not appear in the editor's Project Settings until a project sets them.",
            "",
        ]
    )
    if unregistered:
        sections.extend(["| Setting | What it controls (manifest `effective_state`) |", "| --- | --- |"])
        for key in unregistered:
            sections.append(f"| `{key}` | {_cell(str(entries[key].get('effective_state', '-')))} |")
    else:
        sections.append("None.")
    sections.append("")

    sections.extend(
        [
            "### Deprecated aliases",
            "Old key spellings still read when a project sets them explicitly; see the [migration notes](gaussian-project-settings-migration.md).",
            "",
        ]
    )
    if aliases:
        sections.extend(["| Setting | Manifest note |", "| --- | --- |"])
        for key in aliases:
            sections.append(f"| `{key}` | {_cell(str(entries[key].get('notes', entries[key].get('effective_state', '-'))))} |")
    else:
        sections.append("None.")
    sections.append("")

    sections.extend(
        [
            "## Examples",
            "```bash",
            "python3 scripts/generate_project_settings_reference.py",
            "python3 tests/ci/check_project_settings_reference.py",
            "```",
            "",
            "## Troubleshooting",
            "| Issue | Cause | Fix |",
            "| --- | --- | --- |",
            "| Generation fails: key missing from the manifest | Code registers a key the manifest does not list. | Add the key to `project_settings_manifest.json` (the manifest guard requires it too), then regenerate. |",
            "| Generation fails: cannot resolve a key expression | A registration uses a key form the scanner does not understand. | Use a literal, a `const String`/`StringName` constant, a `#define`, or extend the scanner; never drop the registration from the page by hand. |",
            "| Generation fails: conflicting defaults | One key is registered in two places with different defaults. | Make the registrations agree. |",
            "| `check_project_settings_reference.py` fails | This page and the manifest list different keys. | Regenerate this file. |",
            "| `docs-build` reports this page stale | The manifest or a registration changed without regenerating. | Regenerate this file and commit it. |",
        ]
    )
    return "\n".join(sections)


def _source_referenced_keys() -> set[str]:
    """Keys the module source references at all, using the manifest guard's own
    definition (modules/gaussian_splatting/tests/check_project_settings_manifest.py)."""
    import importlib.util

    checker_path = MODULE_ROOT / "tests" / "check_project_settings_manifest.py"
    spec = importlib.util.spec_from_file_location("_gs_project_settings_manifest_check", checker_path)
    if spec is None or spec.loader is None:
        raise GenerationError(f"  - cannot load {checker_path}")
    checker = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(checker)
    return set(checker.collect_source_setting_paths())


def unreferenced_errors(manifest: dict, by_key: dict[str, list[Registration]], referenced: set[str]) -> list[str]:
    """A manifest key that is neither registered nor read cannot be listed as
    'read but not registered' without lying."""
    return [
        f"{key}: in the manifest, but the source neither registers nor reads it"
        for key, entry in sorted(manifest_entries(manifest).items())
        if key not in by_key and not _is_alias(entry) and key not in referenced
    ]


def generate() -> str:
    manifest = load_manifest()
    files = load_sources()
    registrations, errors = collect_registrations(files)
    by_key, model_errors = build_model(manifest, registrations)
    errors.extend(model_errors)
    errors.extend(unreferenced_errors(manifest, by_key, _source_referenced_keys()))
    if errors:
        raise GenerationError("\n".join(f"  - {error}" for error in errors))
    manual_block = extract_manual_block(OUTPUT.read_text(encoding="utf-8")) if OUTPUT.exists() else []
    return build_reference(manifest, by_key, manual_block) + "\n"


def main() -> int:
    try:
        content = generate()
    except GenerationError as exc:
        print("[docs] Project settings reference NOT written; manifest and source disagree:", file=sys.stderr)
        print(str(exc), file=sys.stderr)
        return 1
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    # LF on every platform, so a Windows regeneration is byte-identical to CI's.
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    print(f"[docs] Wrote project settings reference to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
